package nourl.mythicmetals.registry;

import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;
import nourl.mythicmetals.blocks.MythicMetalsAnvils;
import nourl.mythicmetals.blocks.MythicMetalsBlocks;
import nourl.mythicmetals.blocks.MythicMetalsChains;
import nourl.mythicmetals.ores.MythicMetalsOres;

public class RegisterBlocks {

	public static void register() {
		// Ores
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_ore"), new BlockItem(MythicMetalsOres.ADAMANTITE_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_ore"), new BlockItem(MythicMetalsOres.AETHERIUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_ore"), new BlockItem(MythicMetalsOres.AQUARIUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_ore"), new BlockItem(MythicMetalsOres.BANGLUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_ore"), new BlockItem(MythicMetalsOres.CARMOT_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_ore"), new BlockItem(MythicMetalsOres.COPPER_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_ore"), new BlockItem(MythicMetalsOres.KYBER_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_ore"), new BlockItem(MythicMetalsOres.MANGANESE_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_ore"), new BlockItem(MythicMetalsOres.MIDAS_GOLD_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_ore"), new BlockItem(MythicMetalsOres.MYTHRIL_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_ore"), new BlockItem(MythicMetalsOres.ORICHALCUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_ore"), new BlockItem(MythicMetalsOres.OSMIUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_ore"), new BlockItem(MythicMetalsOres.PLATINUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_ore"), new BlockItem(MythicMetalsOres.PROMETHEUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_ore"), new BlockItem(MythicMetalsOres.QUADRILLUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_ore"), new BlockItem(MythicMetalsOres.RUNITE_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_ore"), new BlockItem(MythicMetalsOres.SILVER_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_ore"), new BlockItem(MythicMetalsOres.STARRITE_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_ore"), new BlockItem(MythicMetalsOres.STORMYX_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tantalite_ore"), new BlockItem(MythicMetalsOres.TANTALITE_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tin_ore"), new BlockItem(MythicMetalsOres.TIN_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "truesilver_ore"), new BlockItem(MythicMetalsOres.TRUESILVER_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "unobtainium_ore"), new BlockItem(MythicMetalsOres.UNOBTAINIUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "ur_ore"), new BlockItem(MythicMetalsOres.UR_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "vermiculite_ore"), new BlockItem(MythicMetalsOres.VERMICULITE_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "zinc_ore"), new BlockItem(MythicMetalsOres.ZINC_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS)));

		RegisterBlock("adamantite_ore", MythicMetalsOres.ADAMANTITE_ORE);
		RegisterBlock("aetherium_ore", MythicMetalsOres.AETHERIUM_ORE);
		RegisterBlock("aquarium_ore", MythicMetalsOres.AQUARIUM_ORE);
		RegisterBlock("banglum_ore", MythicMetalsOres.BANGLUM_ORE);
		RegisterBlock("carmot_ore", MythicMetalsOres.CARMOT_ORE);
		RegisterBlock("copper_ore", MythicMetalsOres.COPPER_ORE);
		RegisterBlock("kyber_ore", MythicMetalsOres.KYBER_ORE);
		RegisterBlock("manganese_ore", MythicMetalsOres.MANGANESE_ORE);
		RegisterBlock("midas_gold_ore", MythicMetalsOres.MIDAS_GOLD_ORE);
		RegisterBlock("mythril_ore", MythicMetalsOres.MYTHRIL_ORE);
		RegisterBlock("orichalcum_ore", MythicMetalsOres.ORICHALCUM_ORE);
		RegisterBlock("osmium_ore", MythicMetalsOres.OSMIUM_ORE);
		RegisterBlock("platinum_ore", MythicMetalsOres.PLATINUM_ORE);
		RegisterBlock("prometheum_ore", MythicMetalsOres.PROMETHEUM_ORE);
		RegisterBlock("quadrillum_ore", MythicMetalsOres.QUADRILLUM_ORE);
		RegisterBlock("runite_ore", MythicMetalsOres.RUNITE_ORE);
		RegisterBlock("silver_ore", MythicMetalsOres.SILVER_ORE);
		RegisterBlock("starrite_ore", MythicMetalsOres.STARRITE_ORE);
		RegisterBlock("stormyx_ore", MythicMetalsOres.STORMYX_ORE);
		RegisterBlock("tantalite_ore", MythicMetalsOres.TANTALITE_ORE);
		RegisterBlock("tin_ore", MythicMetalsOres.TIN_ORE);
		RegisterBlock("truesilver_ore", MythicMetalsOres.TRUESILVER_ORE);
		RegisterBlock("unobtainium_ore", MythicMetalsOres.UNOBTAINIUM_ORE);
		RegisterBlock("ur_ore", MythicMetalsOres.UR_ORE);
		RegisterBlock("vermiculite_ore", MythicMetalsOres.VERMICULITE_ORE);
		RegisterBlock("zinc_ore", MythicMetalsOres.ZINC_ORE);

		// Storage Blocks
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_block"), new BlockItem(MythicMetalsBlocks.ADAMANTITE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_block"), new BlockItem(MythicMetalsBlocks.AETHERIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_block"), new BlockItem(MythicMetalsBlocks.AQUARIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_block"), new BlockItem(MythicMetalsBlocks.ARGONIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_block"), new BlockItem(MythicMetalsBlocks.BANGLUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "brass_block"), new BlockItem(MythicMetalsBlocks.BRASS_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_block"), new BlockItem(MythicMetalsBlocks.BRONZE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_block"), new BlockItem(MythicMetalsBlocks.CARMOT_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_block"), new BlockItem(MythicMetalsBlocks.CELESTIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_block"), new BlockItem(MythicMetalsBlocks.COPPER_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_block"), new BlockItem(MythicMetalsBlocks.DISCORDIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_block"), new BlockItem(MythicMetalsBlocks.DURASTEEL_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_block"), new BlockItem(MythicMetalsBlocks.ELECTRUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_block"), new BlockItem(MythicMetalsBlocks.ETHERITE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_block"), new BlockItem(MythicMetalsBlocks.HALLOWED_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_block"), new BlockItem(MythicMetalsBlocks.KYBER_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_block"), new BlockItem(MythicMetalsBlocks.MANGANESE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_block"), new BlockItem(MythicMetalsBlocks.METALLURGIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_block"), new BlockItem(MythicMetalsBlocks.MIDAS_GOLD_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_block"), new BlockItem(MythicMetalsBlocks.MYTHRIL_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_block"), new BlockItem(MythicMetalsBlocks.ORICHALCUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_block"), new BlockItem(MythicMetalsBlocks.OSMIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_block"), new BlockItem(MythicMetalsBlocks.PLATINUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_block"), new BlockItem(MythicMetalsBlocks.PROMETHEUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_block"), new BlockItem(MythicMetalsBlocks.QUADRILLUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_block"), new BlockItem(MythicMetalsBlocks.QUICKSILVER_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_block"), new BlockItem(MythicMetalsBlocks.RUNITE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_block"), new BlockItem(MythicMetalsBlocks.SILVER_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "slowsilver_block"), new BlockItem(MythicMetalsBlocks.SLOWSILVER_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_block"), new BlockItem(MythicMetalsBlocks.STARRITE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_block"), new BlockItem(MythicMetalsBlocks.STEEL_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_block"), new BlockItem(MythicMetalsBlocks.STORMYX_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tantalite_block"), new BlockItem(MythicMetalsBlocks.TANTALITE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tin_block"), new BlockItem(MythicMetalsBlocks.TIN_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "truesilver_block"), new BlockItem(MythicMetalsBlocks.TRUESILVER_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "unobtainium_block"), new BlockItem(MythicMetalsBlocks.UNOBTAINIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "ur_block"), new BlockItem(MythicMetalsBlocks.UR_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "vermiculite_block"), new BlockItem(MythicMetalsBlocks.VERMICULITE_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "zinc_block"), new BlockItem(MythicMetalsBlocks.ZINC_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS)));

		RegisterBlock("adamantite_block", MythicMetalsBlocks.ADAMANTITE_BLOCK);
		RegisterBlock("aetherium_block", MythicMetalsBlocks.AETHERIUM_BLOCK);
		RegisterBlock("aquarium_block", MythicMetalsBlocks.AQUARIUM_BLOCK);
		RegisterBlock("argonium_block", MythicMetalsBlocks.ARGONIUM_BLOCK);
		RegisterBlock("banglum_block", MythicMetalsBlocks.BANGLUM_BLOCK);
		RegisterBlock("brass_block", MythicMetalsBlocks.BRASS_BLOCK);
		RegisterBlock("bronze_block", MythicMetalsBlocks.BRONZE_BLOCK);
		RegisterBlock("carmot_block", MythicMetalsBlocks.CARMOT_BLOCK);
		RegisterBlock("celestium_block", MythicMetalsBlocks.CELESTIUM_BLOCK);
		RegisterBlock("copper_block", MythicMetalsBlocks.COPPER_BLOCK);
		RegisterBlock("discordium_block", MythicMetalsBlocks.DISCORDIUM_BLOCK);
		RegisterBlock("durasteel_block", MythicMetalsBlocks.DURASTEEL_BLOCK);
		RegisterBlock("electrum_block", MythicMetalsBlocks.ELECTRUM_BLOCK);
		RegisterBlock("etherite_block", MythicMetalsBlocks.ETHERITE_BLOCK);
		RegisterBlock("hallowed_block", MythicMetalsBlocks.HALLOWED_BLOCK);
		RegisterBlock("kyber_block", MythicMetalsBlocks.KYBER_BLOCK);
		RegisterBlock("manganese_block", MythicMetalsBlocks.MANGANESE_BLOCK);
		RegisterBlock("metallurgium_block", MythicMetalsBlocks.METALLURGIUM_BLOCK);
		RegisterBlock("midas_gold_block", MythicMetalsBlocks.MIDAS_GOLD_BLOCK);
		RegisterBlock("mythril_block", MythicMetalsBlocks.MYTHRIL_BLOCK);
		RegisterBlock("orichalcum_block", MythicMetalsBlocks.ORICHALCUM_BLOCK);
		RegisterBlock("osmium_block", MythicMetalsBlocks.OSMIUM_BLOCK);
		RegisterBlock("platinum_block", MythicMetalsBlocks.PLATINUM_BLOCK);
		RegisterBlock("prometheum_block", MythicMetalsBlocks.PROMETHEUM_BLOCK);
		RegisterBlock("quadrillum_block", MythicMetalsBlocks.QUADRILLUM_BLOCK);
		RegisterBlock("quicksilver_block", MythicMetalsBlocks.QUICKSILVER_BLOCK);
		RegisterBlock("runite_block", MythicMetalsBlocks.RUNITE_BLOCK);
		RegisterBlock("silver_block", MythicMetalsBlocks.SILVER_BLOCK);
		RegisterBlock("slowsilver_block", MythicMetalsBlocks.SLOWSILVER_BLOCK);
		RegisterBlock("starrite_block", MythicMetalsBlocks.STARRITE_BLOCK);
		RegisterBlock("steel_block", MythicMetalsBlocks.STEEL_BLOCK);
		RegisterBlock("stormyx_block", MythicMetalsBlocks.STORMYX_BLOCK);
		RegisterBlock("tantalite_block", MythicMetalsBlocks.TANTALITE_BLOCK );
		RegisterBlock("tin_block", MythicMetalsBlocks.TIN_BLOCK);
		RegisterBlock("truesilver_block", MythicMetalsBlocks.TRUESILVER_BLOCK);
		RegisterBlock("unobtainium_block", MythicMetalsBlocks.UNOBTAINIUM_BLOCK);
		RegisterBlock("ur_block", MythicMetalsBlocks.UR_BLOCK);
		RegisterBlock("vermiculite_block", MythicMetalsBlocks.VERMICULITE_BLOCK);
		RegisterBlock("zinc_block", MythicMetalsBlocks.ZINC_BLOCK);

		// Anvils
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_anvil"), new BlockItem(MythicMetalsAnvils.ADAMANTITE_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_anvil"), new BlockItem(MythicMetalsAnvils.AETHERIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_anvil"), new BlockItem(MythicMetalsAnvils.AQUARIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_anvil"), new BlockItem(MythicMetalsAnvils.ARGONIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_anvil"), new BlockItem(MythicMetalsAnvils.BANGLUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "brass_anvil"), new BlockItem(MythicMetalsAnvils.BRASS_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_anvil"), new BlockItem(MythicMetalsAnvils.BRONZE_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_anvil"), new BlockItem(MythicMetalsAnvils.CARMOT_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_anvil"), new BlockItem(MythicMetalsAnvils.CELESTIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_anvil"), new BlockItem(MythicMetalsAnvils.DISCORDIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_anvil"), new BlockItem(MythicMetalsAnvils.DURASTEEL_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_anvil"), new BlockItem(MythicMetalsAnvils.ELECTRUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_anvil"), new BlockItem(MythicMetalsAnvils.ETHERITE_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_anvil"), new BlockItem(MythicMetalsAnvils.HALLOWED_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_anvil"), new BlockItem(MythicMetalsAnvils.KYBER_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_anvil"), new BlockItem(MythicMetalsAnvils.MANGANESE_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_anvil"), new BlockItem(MythicMetalsAnvils.METALLURGIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR).fireproof()));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_anvil"), new BlockItem(MythicMetalsAnvils.MIDAS_GOLD_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_anvil"), new BlockItem(MythicMetalsAnvils.MYTHRIL_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_anvil"), new BlockItem(MythicMetalsAnvils.ORICHALCUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_anvil"), new BlockItem(MythicMetalsAnvils.OSMIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_anvil"), new BlockItem(MythicMetalsAnvils.PLATINUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_anvil"), new BlockItem(MythicMetalsAnvils.PROMETHEUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_anvil"), new BlockItem(MythicMetalsAnvils.QUADRILLUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_anvil"), new BlockItem(MythicMetalsAnvils.QUICKSILVER_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_anvil"), new BlockItem(MythicMetalsAnvils.RUNITE_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_anvil"), new BlockItem(MythicMetalsAnvils.SILVER_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "slowsilver_anvil"), new BlockItem(MythicMetalsAnvils.SLOWSILVER_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_anvil"), new BlockItem(MythicMetalsAnvils.STARRITE_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_anvil"), new BlockItem(MythicMetalsAnvils.STEEL_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_anvil"), new BlockItem(MythicMetalsAnvils.STORMYX_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tantalite_anvil"), new BlockItem(MythicMetalsAnvils.TANTALITE_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "truesilver_anvil"), new BlockItem(MythicMetalsAnvils.TRUESILVER_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "ur_anvil"), new BlockItem(MythicMetalsAnvils.UR_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));

		RegisterBlock("adamantite_anvil", MythicMetalsAnvils.ADAMANTITE_ANVIL);
		RegisterBlock("aetherium_anvil", MythicMetalsAnvils.AETHERIUM_ANVIL);
		RegisterBlock("aquarium_anvil", MythicMetalsAnvils.AQUARIUM_ANVIL);
		RegisterBlock("argonium_anvil", MythicMetalsAnvils.ARGONIUM_ANVIL);
		RegisterBlock("banglum_anvil", MythicMetalsAnvils.BANGLUM_ANVIL);
		RegisterBlock("brass_anvil", MythicMetalsAnvils.BRASS_ANVIL);
		RegisterBlock("bronze_anvil", MythicMetalsAnvils.BRONZE_ANVIL);
		RegisterBlock("carmot_anvil", MythicMetalsAnvils.CARMOT_ANVIL);
		RegisterBlock("celestium_anvil", MythicMetalsAnvils.CELESTIUM_ANVIL);
		RegisterBlock("discordium_anvil", MythicMetalsAnvils.DISCORDIUM_ANVIL);
		RegisterBlock("durasteel_anvil", MythicMetalsAnvils.DURASTEEL_ANVIL);
		RegisterBlock("electrum_anvil", MythicMetalsAnvils.ELECTRUM_ANVIL);
		RegisterBlock("etherite_anvil", MythicMetalsAnvils.ETHERITE_ANVIL);
		RegisterBlock("hallowed_anvil",MythicMetalsAnvils.HALLOWED_ANVIL);
		RegisterBlock("kyber_anvil",MythicMetalsAnvils.KYBER_ANVIL);
		RegisterBlock("manganese_anvil",MythicMetalsAnvils.MANGANESE_ANVIL);
		RegisterBlock("metallurgium_anvil",MythicMetalsAnvils.METALLURGIUM_ANVIL);
		RegisterBlock("midas_gold_anvil", MythicMetalsAnvils.MIDAS_GOLD_ANVIL);
		RegisterBlock("mythril_anvil", MythicMetalsAnvils.MYTHRIL_ANVIL);
		RegisterBlock("orichalcum_anvil",MythicMetalsAnvils.ORICHALCUM_ANVIL);
		RegisterBlock("osmium_anvil", MythicMetalsAnvils.OSMIUM_ANVIL);
		RegisterBlock("platinum_anvil", MythicMetalsAnvils.PLATINUM_ANVIL);
		RegisterBlock("prometheum_anvil", MythicMetalsAnvils.PROMETHEUM_ANVIL);
		RegisterBlock("quadrillum_anvil", MythicMetalsAnvils.QUADRILLUM_ANVIL);
		RegisterBlock("quicksilver_anvil", MythicMetalsAnvils.QUICKSILVER_ANVIL);
		RegisterBlock("runite_anvil", MythicMetalsAnvils.RUNITE_ANVIL);
		RegisterBlock("silver_anvil", MythicMetalsAnvils.SILVER_ANVIL);
		RegisterBlock("slowsilver_anvil", MythicMetalsAnvils.SLOWSILVER_ANVIL);
		RegisterBlock("starrite_anvil", MythicMetalsAnvils.STARRITE_ANVIL);
		RegisterBlock("steel_anvil", MythicMetalsAnvils.STEEL_ANVIL);
		RegisterBlock("stormyx_anvil", MythicMetalsAnvils.STORMYX_ANVIL);
		RegisterBlock("tantalite_anvil",MythicMetalsAnvils.TANTALITE_ANVIL );
		RegisterBlock("truesilver_anvil", MythicMetalsAnvils.TRUESILVER_ANVIL);
		RegisterBlock("ur_anvil", MythicMetalsAnvils.UR_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.ADAMANTITE_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.AETHERIUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.AQUARIUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.ARGONIUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.BANGLUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.BRASS_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.BRONZE_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.CARMOT_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.CELESTIUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.DISCORDIUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.DURASTEEL_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.ELECTRUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.ETHERITE_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.HALLOWED_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.KYBER_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.MANGANESE_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.METALLURGIUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.MIDAS_GOLD_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.MYTHRIL_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.ORICHALCUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.OSMIUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.PLATINUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.PROMETHEUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.QUADRILLUM_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.QUICKSILVER_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.RUNITE_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.SILVER_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.SLOWSILVER_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.STARRITE_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.STEEL_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.STORMYX_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.TANTALITE_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.TRUESILVER_ANVIL);
		MythicMetalsAnvils.ANVILS.add(MythicMetalsAnvils.UR_ANVIL);

		// Chains
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_chain"), new BlockItem(MythicMetalsChains.ADAMANTITE_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_chain"), new BlockItem(MythicMetalsChains.AETHERIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_chain"), new BlockItem(MythicMetalsChains.AQUARIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_chain"), new BlockItem(MythicMetalsChains.ARGONIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_chain"), new BlockItem(MythicMetalsChains.BANGLUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "brass_chain"), new BlockItem(MythicMetalsChains.BRASS_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_chain"), new BlockItem(MythicMetalsChains.BRONZE_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_chain"), new BlockItem(MythicMetalsChains.CARMOT_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_chain"), new BlockItem(MythicMetalsChains.CELESTIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_chain"), new BlockItem(MythicMetalsChains.DISCORDIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_chain"), new BlockItem(MythicMetalsChains.DURASTEEL_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_chain"), new BlockItem(MythicMetalsChains.ELECTRUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_chain"), new BlockItem(MythicMetalsChains.ETHERITE_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_chain"), new BlockItem(MythicMetalsChains.HALLOWED_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_chain"), new BlockItem(MythicMetalsChains.KYBER_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_chain"), new BlockItem(MythicMetalsChains.MANGANESE_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_chain"), new BlockItem(MythicMetalsChains.METALLURGIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR).fireproof()));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_chain"), new BlockItem(MythicMetalsChains.MIDAS_GOLD_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_chain"), new BlockItem(MythicMetalsChains.MYTHRIL_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_chain"), new BlockItem(MythicMetalsChains.ORICHALCUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_chain"), new BlockItem(MythicMetalsChains.OSMIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_chain"), new BlockItem(MythicMetalsChains.PLATINUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_chain"), new BlockItem(MythicMetalsChains.PROMETHEUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_chain"), new BlockItem(MythicMetalsChains.QUADRILLUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_chain"), new BlockItem(MythicMetalsChains.QUICKSILVER_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_chain"), new BlockItem(MythicMetalsChains.RUNITE_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_chain"), new BlockItem(MythicMetalsChains.SILVER_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "slowsilver_chain"), new BlockItem(MythicMetalsChains.SLOWSILVER_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_chain"), new BlockItem(MythicMetalsChains.STARRITE_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_chain"), new BlockItem(MythicMetalsChains.STEEL_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_chain"), new BlockItem(MythicMetalsChains.STORMYX_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tantalite_chain"), new BlockItem(MythicMetalsChains.TANTALITE_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "truesilver_chain"), new BlockItem(MythicMetalsChains.TRUESILVER_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "ur_chain"), new BlockItem(MythicMetalsChains.UR_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));

		RegisterBlock("adamantite_chain", MythicMetalsChains.ADAMANTITE_CHAIN);
		RegisterBlock("aetherium_chain", MythicMetalsChains.AETHERIUM_CHAIN);
		RegisterBlock("aquarium_chain", MythicMetalsChains.AQUARIUM_CHAIN);
		RegisterBlock("argonium_chain", MythicMetalsChains.ARGONIUM_CHAIN);
		RegisterBlock("banglum_chain", MythicMetalsChains.BANGLUM_CHAIN);
		RegisterBlock("brass_chain", MythicMetalsChains.BRASS_CHAIN);
		RegisterBlock("bronze_chain", MythicMetalsChains.BRONZE_CHAIN);
		RegisterBlock("carmot_chain", MythicMetalsChains.CARMOT_CHAIN);
		RegisterBlock("celestium_chain", MythicMetalsChains.CELESTIUM_CHAIN);
		RegisterBlock("discordium_chain", MythicMetalsChains.DISCORDIUM_CHAIN);
		RegisterBlock("durasteel_chain", MythicMetalsChains.DURASTEEL_CHAIN);
		RegisterBlock("electrum_chain", MythicMetalsChains.ELECTRUM_CHAIN);
		RegisterBlock("etherite_chain", MythicMetalsChains.ETHERITE_CHAIN);
		RegisterBlock("hallowed_chain", MythicMetalsChains.HALLOWED_CHAIN);
		RegisterBlock("kyber_chain", MythicMetalsChains.KYBER_CHAIN);
		RegisterBlock("manganese_chain",MythicMetalsChains.MANGANESE_CHAIN);
		RegisterBlock("metallurgium_chain",MythicMetalsChains.METALLURGIUM_CHAIN);
		RegisterBlock("midas_gold_chain", MythicMetalsChains.MIDAS_GOLD_CHAIN);
		RegisterBlock("mythril_chain", MythicMetalsChains.MYTHRIL_CHAIN);
		RegisterBlock("orichalcum_chain",MythicMetalsChains.ORICHALCUM_CHAIN);
		RegisterBlock("osmium_chain", MythicMetalsChains.OSMIUM_CHAIN);
		RegisterBlock("platinum_chain", MythicMetalsChains.PLATINUM_CHAIN);
		RegisterBlock("prometheum_chain", MythicMetalsChains.PROMETHEUM_CHAIN);
		RegisterBlock("quadrillum_chain", MythicMetalsChains.QUADRILLUM_CHAIN);
		RegisterBlock("quicksilver_chain", MythicMetalsChains.QUICKSILVER_CHAIN);
		RegisterBlock("runite_chain", MythicMetalsChains.RUNITE_CHAIN);
		RegisterBlock("silver_chain", MythicMetalsChains.SILVER_CHAIN);
		RegisterBlock("slowsilver_chain", MythicMetalsChains.SLOWSILVER_CHAIN);
		RegisterBlock("starrite_chain", MythicMetalsChains.STARRITE_CHAIN);
		RegisterBlock("steel_chain", MythicMetalsChains.STEEL_CHAIN);
		RegisterBlock("stormyx_chain", MythicMetalsChains.STORMYX_CHAIN);
		RegisterBlock("tantalite_chain",MythicMetalsChains.TANTALITE_CHAIN );
		RegisterBlock("truesilver_chain", MythicMetalsChains.TRUESILVER_CHAIN);
		RegisterBlock("ur_chain", MythicMetalsChains.UR_CHAIN);
	}
	public static void RegisterBlock(String path, Block block) {
		Registry.register(Registry.BLOCK, new Identifier(MythicMetals.MOD_ID, path), block);
	}
	public static void RegisterItem(String path, Block block) {
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, path), new BlockItem(block, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
	}
}
