package nourl.mythicmetals.registry;

import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;

public class RegisterItems {
    //Normal Ingots
    public static final Item ADAMANTITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AETHERIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AQUARIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ARGONIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BANGLUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BRASS_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BRONZE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CARMOT_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CELESTIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item COPPER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DISCORDIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DURASTEEL_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ELECTRUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ETHERITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item HALLOWED_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item KYBER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MANGANESE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item METALLURGIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item MIDAS_GOLD_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MYTHRIL_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ORICHALCUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item OSMIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PLATINUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PROMETHEUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUADRILLUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUICKSILVER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RUNITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item SILVER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item SLOWSILVER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STARRITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STEEL_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STORMYX_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TANTALITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TIN_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TRUESILVER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item UNOBTAINIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item UR_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item VERMICULITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ZINC_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));

    public static final Item ADAMANTITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AETHERIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AQUARIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ARGONIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BANGLUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BRASS_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BRONZE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CARMOT_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CELESTIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item COPPER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DISCORDIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DURASTEEL_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ELECTRUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ETHERITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item GOLD_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item HALLOWED_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item KYBER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MANGANESE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item METALLURGIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item MIDAS_GOLD_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MYTHRIL_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ORICHALCUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item OSMIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PLATINUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PROMETHEUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUADRILLUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUICKSILVER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RUNITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item SILVER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item SLOWSILVER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STARRITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STEEL_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STORMYX_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TANTALITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TIN_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TRUESILVER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item UR_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ZINC_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));

    public static final Item RAW_ADAMANTITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_AETHERIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_AQUARIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_ARGONIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_BANGLUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_BRASS = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_BRONZE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_CARMOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_CELESTIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_COPPER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_DISCORDIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_DURASTEEL = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_ELECTRUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_ETHERITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_GOLD = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_HALLOWED = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_KYBER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_MANGANESE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_METALLURGIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item RAW_MIDAS_GOLD = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_MYTHRIL = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_ORICHALCUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_OSMIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_PLATINUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_PROMETHEUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_QUADRILLUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_QUICKSILVER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_RUNITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_SILVER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_SLOWSILVER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_STARRITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_STEEL = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_STORMYX = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_TANTALITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_TIN = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_TRUESILVER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_UR = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_ZINC = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));


public static void registerDusts() {
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_dust"), ADAMANTITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_dust"), AETHERIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_dust"), AQUARIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_dust"), ARGONIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_dust"), BANGLUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "brass_dust"), BRASS_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_dust"), BRONZE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_dust"), CARMOT_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_dust"), CELESTIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_dust"), COPPER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_dust"), DISCORDIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_dust"), DURASTEEL_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_dust"), ELECTRUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_dust"), ETHERITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "gold_dust"), GOLD_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_dust"), HALLOWED_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_dust"), KYBER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_dust"), MANGANESE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_dust"), METALLURGIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_dust"), MIDAS_GOLD_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_dust"), MYTHRIL_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_dust"), ORICHALCUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_dust"), OSMIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_dust"), PLATINUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_dust"), PROMETHEUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_dust"), QUADRILLUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_dust"), QUICKSILVER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_dust"), RUNITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_dust"), SILVER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "slowsilver_dust"), SLOWSILVER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_dust"), STARRITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_dust"), STEEL_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_dust"), STORMYX_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tantalite_dust"), TANTALITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tin_dust"), TIN_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "truesilver_dust"), TRUESILVER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "unobtainium"), UNOBTAINIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "ur_dust"), UR_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "vermiculite"), VERMICULITE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "zinc_dust"), ZINC_DUST);
}
public static void registerItems() {
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_adamantite"), RAW_ADAMANTITE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_aetherium"), RAW_AETHERIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_aquarium"), RAW_AQUARIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_argonium"), RAW_ARGONIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_banglum"), RAW_BANGLUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_brass"), RAW_BRASS);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_bronze"), RAW_BRONZE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_carmot"), RAW_CARMOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_celestium"), RAW_CELESTIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_copper"), RAW_COPPER);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_discordium"), RAW_DISCORDIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_durasteel"), RAW_DURASTEEL);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_electrum"), RAW_ELECTRUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_etherite"), RAW_ETHERITE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_gold"), RAW_GOLD);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_hallowed"), RAW_HALLOWED);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_kyber"), RAW_KYBER);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_manganese"), RAW_MANGANESE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_metallurgium"), RAW_METALLURGIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_midas_gold"), RAW_MIDAS_GOLD);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_mythril"), RAW_MYTHRIL);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_orichalcum"), RAW_ORICHALCUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_osmium"), RAW_OSMIUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_platinum"), RAW_PLATINUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_prometheum"), RAW_PROMETHEUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_quadrillum"), RAW_QUADRILLUM);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_quicksilver"), RAW_QUICKSILVER);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_runite"), RAW_RUNITE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_silver"), RAW_SILVER);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_slowsilver"), RAW_SLOWSILVER);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_starrite"), RAW_STARRITE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_steel"), RAW_STEEL);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_stormyx"), RAW_STORMYX);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_tantalite"), RAW_TANTALITE);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_tin"), RAW_TIN);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_truesilver"), RAW_TRUESILVER);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_ur"), RAW_UR);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_zinc"), RAW_ZINC);

    //Register Ingots
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_ingot"), ADAMANTITE_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_ingot"), AETHERIUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_ingot"), AQUARIUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_ingot"), ARGONIUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_ingot"), BANGLUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "brass_ingot"), BRASS_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_ingot"), BRONZE_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_ingot"), CARMOT_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_ingot"), CELESTIUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_ingot"), COPPER_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_ingot"), DISCORDIUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_ingot"), DURASTEEL_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_ingot"), ELECTRUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_ingot"), ETHERITE_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_ingot"), HALLOWED_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_ingot"), KYBER_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_ingot"), MANGANESE_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_ingot"), METALLURGIUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_ingot"), MIDAS_GOLD_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_ingot"), MYTHRIL_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_ingot"), ORICHALCUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_ingot"), OSMIUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_ingot"), PLATINUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_ingot"), PROMETHEUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_ingot"), QUADRILLUM_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_ingot"), QUICKSILVER_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_ingot"), RUNITE_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_ingot"), SILVER_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "slowsilver_ingot"), SLOWSILVER_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_ingot"), STARRITE_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_ingot"), STEEL_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_ingot"), STORMYX_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tantalite_ingot"), TANTALITE_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tin_ingot"), TIN_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "truesilver_ingot"), TRUESILVER_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "ur_ingot"), UR_INGOT);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "zinc_ingot"), ZINC_INGOT);
    }
}
