package nourl.mythicmetals.registry;

import net.minecraft.item.Item;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.SwordItem;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;
import nourl.mythicmetals.tools.AxeBase;
import nourl.mythicmetals.tools.HoeBase;
import nourl.mythicmetals.tools.MythicMetalsToolMaterials;
import nourl.mythicmetals.tools.PickaxeBase;

public class RegisterTools {
	//SWORDS
	public static final Item ADAMANTITE_SWORD = new SwordItem(MythicMetalsToolMaterials.ADAMANTITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AETHERIUM_SWORD = new SwordItem(MythicMetalsToolMaterials.AETHERIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AQUARIUM_SWORD = new SwordItem(MythicMetalsToolMaterials.AQUARIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ARGONIUM_SWORD = new SwordItem(MythicMetalsToolMaterials.ARGONIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BANGLUM_SWORD = new SwordItem(MythicMetalsToolMaterials.BANGLUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRASS_SWORD = new SwordItem(MythicMetalsToolMaterials.BRASS, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRONZE_SWORD = new SwordItem(MythicMetalsToolMaterials.BRONZE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CARMOT_SWORD = new SwordItem(MythicMetalsToolMaterials.CARMOT, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CELESTIUM_SWORD = new SwordItem(MythicMetalsToolMaterials.CELESTIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item COPPER_SWORD = new SwordItem(MythicMetalsToolMaterials.COPPER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DISCORDIUM_SWORD = new SwordItem(MythicMetalsToolMaterials.DISCORDIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DURASTEEL_SWORD = new SwordItem(MythicMetalsToolMaterials.DURASTEEL, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ELECTRUM_SWORD = new SwordItem(MythicMetalsToolMaterials.ELECTRUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ETHERITE_SWORD = new SwordItem(MythicMetalsToolMaterials.ETHERITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item HALLOWED_SWORD = new SwordItem(MythicMetalsToolMaterials.HALLOWED, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item KYBER_SWORD = new SwordItem(MythicMetalsToolMaterials.KYBER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item METALLURGIUM_SWORD = new SwordItem(MythicMetalsToolMaterials.METALLURGIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
	public static final Item MIDAS_GOLD_SWORD = new SwordItem(MythicMetalsToolMaterials.MIDAS_GOLD, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item MYTHRIL_SWORD = new SwordItem(MythicMetalsToolMaterials.MYTHRIL, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ORICHALCUM_SWORD = new SwordItem(MythicMetalsToolMaterials.ORICHALCUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item OSMIUM_SWORD = new SwordItem(MythicMetalsToolMaterials.OSMIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PLATINUM_SWORD = new SwordItem(MythicMetalsToolMaterials.PLATINUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PROMETHEUM_SWORD = new SwordItem(MythicMetalsToolMaterials.PROMETHEUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUADRILLUM_SWORD = new SwordItem(MythicMetalsToolMaterials.QUADRILLUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUICKSILVER_SWORD = new SwordItem(MythicMetalsToolMaterials.QUICKSILVER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item RUNITE_SWORD = new SwordItem(MythicMetalsToolMaterials.RUNITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SILVER_SWORD = new SwordItem(MythicMetalsToolMaterials.SILVER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SLOWSILVER_SWORD = new SwordItem(MythicMetalsToolMaterials.SLOWSILVER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STARRITE_SWORD = new SwordItem(MythicMetalsToolMaterials.STARRITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STEEL_SWORD = new SwordItem(MythicMetalsToolMaterials.STEEL, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STORMYX_SWORD = new SwordItem(MythicMetalsToolMaterials.STORMYX, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TANTALITE_SWORD = new SwordItem(MythicMetalsToolMaterials.TANTALITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TIN_SWORD = new SwordItem(MythicMetalsToolMaterials.TIN, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TRUESILVER_SWORD = new SwordItem(MythicMetalsToolMaterials.TRUESILVER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item UR_SWORD = new SwordItem(MythicMetalsToolMaterials.UR, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	//PICKAXES
	public static final Item ADAMANTITE_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.ADAMANTITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AETHERIUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.AETHERIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AQUARIUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.AQUARIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ARGONIUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.ARGONIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BANGLUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.BANGLUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRASS_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.BRASS, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRONZE_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.BRONZE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CARMOT_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.CARMOT, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CELESTIUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.CELESTIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item COPPER_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.COPPER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DISCORDIUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.DISCORDIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DURASTEEL_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.DURASTEEL, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ELECTRUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.ELECTRUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ETHERITE_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.ETHERITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item HALLOWED_PICKAXE = new SwordItem(MythicMetalsToolMaterials.HALLOWED, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item KYBER_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.KYBER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item METALLURGIUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.METALLURGIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
	public static final Item MIDAS_GOLD_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.MIDAS_GOLD, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item MYTHRIL_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.MYTHRIL, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ORICHALCUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.ORICHALCUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item OSMIUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.OSMIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PLATINUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.PLATINUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PROMETHEUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.PROMETHEUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUADRILLUM_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.QUADRILLUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUICKSILVER_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.QUICKSILVER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item RUNITE_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.RUNITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SILVER_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.SILVER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SLOWSILVER_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.SLOWSILVER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STARRITE_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.STARRITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STEEL_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.STEEL, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STORMYX_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.STORMYX, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TANTALITE_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.TANTALITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TIN_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.TIN, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TRUESILVER_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.TRUESILVER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item UR_PICKAXE = new PickaxeBase(MythicMetalsToolMaterials.UR, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	//AXES
	public static final Item ADAMANTITE_AXE = new AxeBase(MythicMetalsToolMaterials.ADAMANTITE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AETHERIUM_AXE = new AxeBase(MythicMetalsToolMaterials.AETHERIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AQUARIUM_AXE = new AxeBase(MythicMetalsToolMaterials.AQUARIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ARGONIUM_AXE = new AxeBase(MythicMetalsToolMaterials.ARGONIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BANGLUM_AXE = new AxeBase(MythicMetalsToolMaterials.BANGLUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRASS_AXE = new AxeBase(MythicMetalsToolMaterials.BRASS, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRONZE_AXE = new AxeBase(MythicMetalsToolMaterials.BRONZE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CARMOT_AXE = new AxeBase(MythicMetalsToolMaterials.CARMOT, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CELESTIUM_AXE = new AxeBase(MythicMetalsToolMaterials.CELESTIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item COPPER_AXE = new AxeBase(MythicMetalsToolMaterials.COPPER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DISCORDIUM_AXE = new AxeBase(MythicMetalsToolMaterials.DISCORDIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DURASTEEL_AXE = new AxeBase(MythicMetalsToolMaterials.DURASTEEL, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ELECTRUM_AXE = new AxeBase(MythicMetalsToolMaterials.ELECTRUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ETHERITE_AXE = new AxeBase(MythicMetalsToolMaterials.ETHERITE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item HALLOWED_AXE = new SwordItem(MythicMetalsToolMaterials.HALLOWED, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item KYBER_AXE = new AxeBase(MythicMetalsToolMaterials.KYBER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item METALLURGIUM_AXE = new AxeBase(MythicMetalsToolMaterials.METALLURGIUM, 5, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
	public static final Item MIDAS_GOLD_AXE = new AxeBase(MythicMetalsToolMaterials.MIDAS_GOLD, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item MYTHRIL_AXE = new AxeBase(MythicMetalsToolMaterials.MYTHRIL, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ORICHALCUM_AXE = new AxeBase(MythicMetalsToolMaterials.ORICHALCUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item OSMIUM_AXE = new AxeBase(MythicMetalsToolMaterials.OSMIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PLATINUM_AXE = new AxeBase(MythicMetalsToolMaterials.PLATINUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PROMETHEUM_AXE = new AxeBase(MythicMetalsToolMaterials.PROMETHEUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUADRILLUM_AXE = new AxeBase(MythicMetalsToolMaterials.QUADRILLUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUICKSILVER_AXE = new AxeBase(MythicMetalsToolMaterials.QUICKSILVER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item RUNITE_AXE = new AxeBase(MythicMetalsToolMaterials.RUNITE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SILVER_AXE = new AxeBase(MythicMetalsToolMaterials.SILVER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SLOWSILVER_AXE = new AxeBase(MythicMetalsToolMaterials.SLOWSILVER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STARRITE_AXE = new AxeBase(MythicMetalsToolMaterials.STARRITE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STEEL_AXE = new AxeBase(MythicMetalsToolMaterials.STEEL, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STORMYX_AXE = new AxeBase(MythicMetalsToolMaterials.STORMYX, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TANTALITE_AXE = new AxeBase(MythicMetalsToolMaterials.TANTALITE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TIN_AXE = new AxeBase(MythicMetalsToolMaterials.TIN, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TRUESILVER_AXE = new AxeBase(MythicMetalsToolMaterials.TRUESILVER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item UR_AXE = new AxeBase(MythicMetalsToolMaterials.UR, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	//SHOVELS
	public static final Item ADAMANTITE_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.ADAMANTITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AETHERIUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.AETHERIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AQUARIUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.AQUARIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ARGONIUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.ARGONIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BANGLUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.BANGLUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRASS_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.BRASS, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRONZE_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.BRONZE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CARMOT_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.CARMOT, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CELESTIUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.CELESTIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item COPPER_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.COPPER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DISCORDIUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.DISCORDIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DURASTEEL_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.DURASTEEL, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ELECTRUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.ELECTRUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ETHERITE_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.ETHERITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item HALLOWED_SHOVEL = new SwordItem(MythicMetalsToolMaterials.HALLOWED, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item KYBER_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.KYBER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item METALLURGIUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.METALLURGIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
	public static final Item MIDAS_GOLD_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.MIDAS_GOLD, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item MYTHRIL_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.MYTHRIL, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ORICHALCUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.ORICHALCUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item OSMIUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.OSMIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PLATINUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.PLATINUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PROMETHEUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.PROMETHEUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUADRILLUM_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.QUADRILLUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUICKSILVER_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.QUICKSILVER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item RUNITE_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.RUNITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SILVER_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.SILVER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SLOWSILVER_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.SLOWSILVER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STARRITE_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.STARRITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STEEL_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.STEEL, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STORMYX_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.STORMYX, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TANTALITE_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.TANTALITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TIN_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.TIN, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TRUESILVER_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.TRUESILVER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item UR_SHOVEL = new ShovelItem(MythicMetalsToolMaterials.UR, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	//HOES
	public static final Item ADAMANTITE_HOE = new HoeBase(MythicMetalsToolMaterials.ADAMANTITE, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AETHERIUM_HOE = new HoeBase(MythicMetalsToolMaterials.AETHERIUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item AQUARIUM_HOE = new HoeBase(MythicMetalsToolMaterials.AQUARIUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ARGONIUM_HOE = new HoeBase(MythicMetalsToolMaterials.ARGONIUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BANGLUM_HOE = new HoeBase(MythicMetalsToolMaterials.BANGLUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRASS_HOE = new HoeBase(MythicMetalsToolMaterials.BRASS, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item BRONZE_HOE = new HoeBase(MythicMetalsToolMaterials.BRONZE, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CARMOT_HOE = new HoeBase(MythicMetalsToolMaterials.CARMOT, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item CELESTIUM_HOE = new HoeBase(MythicMetalsToolMaterials.CELESTIUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item COPPER_HOE = new HoeBase(MythicMetalsToolMaterials.COPPER, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DISCORDIUM_HOE = new HoeBase(MythicMetalsToolMaterials.DISCORDIUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item DURASTEEL_HOE = new HoeBase(MythicMetalsToolMaterials.DURASTEEL, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ELECTRUM_HOE = new HoeBase(MythicMetalsToolMaterials.ELECTRUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ETHERITE_HOE = new HoeBase(MythicMetalsToolMaterials.ETHERITE, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item HALLOWED_HOE = new SwordItem(MythicMetalsToolMaterials.HALLOWED, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item KYBER_HOE = new HoeBase(MythicMetalsToolMaterials.KYBER, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item METALLURGIUM_HOE = new HoeBase(MythicMetalsToolMaterials.METALLURGIUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
	public static final Item MIDAS_GOLD_HOE = new HoeBase(MythicMetalsToolMaterials.MIDAS_GOLD, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item MYTHRIL_HOE = new HoeBase(MythicMetalsToolMaterials.MYTHRIL, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item ORICHALCUM_HOE = new HoeBase(MythicMetalsToolMaterials.ORICHALCUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item OSMIUM_HOE = new HoeBase(MythicMetalsToolMaterials.OSMIUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PLATINUM_HOE = new HoeBase(MythicMetalsToolMaterials.PLATINUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item PROMETHEUM_HOE = new HoeBase(MythicMetalsToolMaterials.PROMETHEUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUADRILLUM_HOE = new HoeBase(MythicMetalsToolMaterials.QUADRILLUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item QUICKSILVER_HOE = new HoeBase(MythicMetalsToolMaterials.QUICKSILVER, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item RUNITE_HOE = new HoeBase(MythicMetalsToolMaterials.RUNITE, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SILVER_HOE = new HoeBase(MythicMetalsToolMaterials.SILVER, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item SLOWSILVER_HOE = new HoeBase(MythicMetalsToolMaterials.SLOWSILVER, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STARRITE_HOE = new HoeBase(MythicMetalsToolMaterials.STARRITE, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STEEL_HOE = new HoeBase(MythicMetalsToolMaterials.STEEL, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item STORMYX_HOE = new HoeBase(MythicMetalsToolMaterials.STORMYX, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TANTALITE_HOE = new HoeBase(MythicMetalsToolMaterials.TANTALITE, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TIN_HOE = new HoeBase(MythicMetalsToolMaterials.TIN, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item TRUESILVER_HOE = new HoeBase(MythicMetalsToolMaterials.TRUESILVER, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	public static final Item UR_HOE = new HoeBase(MythicMetalsToolMaterials.UR, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
	
	
	
	public static void register() {
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"adamantite_axe"),ADAMANTITE_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"adamantite_hoe"),ADAMANTITE_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"adamantite_pickaxe"),ADAMANTITE_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"adamantite_shovel"),ADAMANTITE_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"adamantite_sword"),ADAMANTITE_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aetherium_axe"),AETHERIUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aetherium_hoe"),AETHERIUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aetherium_pickaxe"),AETHERIUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aetherium_shovel"),AETHERIUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aetherium_sword"),AETHERIUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aquarium_axe"),AQUARIUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aquarium_hoe"),AQUARIUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aquarium_pickaxe"),AQUARIUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aquarium_shovel"),AQUARIUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"aquarium_sword"),AQUARIUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"argonium_axe"),ARGONIUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"argonium_hoe"),ARGONIUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"argonium_pickaxe"),ARGONIUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"argonium_shovel"),ARGONIUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"argonium_sword"),ARGONIUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"banglum_axe"),BANGLUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"banglum_hoe"),BANGLUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"banglum_pickaxe"),BANGLUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"banglum_shovel"),BANGLUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"banglum_sword"),BANGLUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"brass_axe"),BRASS_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"brass_hoe"),BRASS_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"brass_pickaxe"),BRASS_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"brass_shovel"),BRASS_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"brass_sword"),BRASS_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"bronze_axe"),BRONZE_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"bronze_hoe"),BRONZE_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"bronze_pickaxe"),BRONZE_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"bronze_shovel"),BRONZE_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"bronze_sword"),BRONZE_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"carmot_axe"),CARMOT_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"carmot_hoe"),CARMOT_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"carmot_pickaxe"),CARMOT_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"carmot_shovel"),CARMOT_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"carmot_sword"),CARMOT_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"celestium_axe"),CELESTIUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"celestium_hoe"),CELESTIUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"celestium_pickaxe"),CELESTIUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"celestium_shovel"),CELESTIUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"celestium_sword"),CELESTIUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"copper_axe"),COPPER_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"copper_hoe"),COPPER_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"copper_pickaxe"),COPPER_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"copper_shovel"),COPPER_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"copper_sword"),COPPER_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"discordium_axe"),DISCORDIUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"discordium_hoe"),DISCORDIUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"discordium_pickaxe"),DISCORDIUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"discordium_shovel"),DISCORDIUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"discordium_sword"),DISCORDIUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"durasteel_axe"),DURASTEEL_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"durasteel_hoe"),DURASTEEL_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"durasteel_pickaxe"),DURASTEEL_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"durasteel_shovel"),DURASTEEL_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"durasteel_sword"),DURASTEEL_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"electrum_axe"),ELECTRUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"electrum_hoe"),ELECTRUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"electrum_pickaxe"),ELECTRUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"electrum_shovel"),ELECTRUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"electrum_sword"),ELECTRUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"etherite_axe"),ETHERITE_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"etherite_hoe"),ETHERITE_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"etherite_pickaxe"),ETHERITE_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"etherite_shovel"),ETHERITE_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"etherite_sword"),ETHERITE_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"kyber_axe"),KYBER_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"kyber_hoe"),KYBER_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"kyber_pickaxe"),KYBER_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"kyber_shovel"),KYBER_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"kyber_sword"),KYBER_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"hallowed_axe"),HALLOWED_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"hallowed_hoe"),HALLOWED_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"hallowed_pickaxe"),HALLOWED_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"hallowed_shovel"),HALLOWED_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"hallowed_sword"),HALLOWED_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"metallurgium_axe"),METALLURGIUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"metallurgium_hoe"),METALLURGIUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"metallurgium_pickaxe"),METALLURGIUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"metallurgium_shovel"),METALLURGIUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"metallurgium_sword"),METALLURGIUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"midas_gold_axe"),MIDAS_GOLD_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"midas_gold_hoe"),MIDAS_GOLD_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"midas_gold_pickaxe"),MIDAS_GOLD_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"midas_gold_shovel"),MIDAS_GOLD_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"midas_gold_sword"),MIDAS_GOLD_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"mythril_axe"),MYTHRIL_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"mythril_hoe"),MYTHRIL_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"mythril_pickaxe"),MYTHRIL_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"mythril_shovel"),MYTHRIL_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"mythril_sword"),MYTHRIL_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"orichalcum_axe"),ORICHALCUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"orichalcum_hoe"),ORICHALCUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"orichalcum_pickaxe"),ORICHALCUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"orichalcum_shovel"),ORICHALCUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"orichalcum_sword"),ORICHALCUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"osmium_axe"),OSMIUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"osmium_hoe"),OSMIUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"osmium_pickaxe"),OSMIUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"osmium_shovel"),OSMIUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"osmium_sword"),OSMIUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"platinum_axe"),PLATINUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"platinum_hoe"),PLATINUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"platinum_pickaxe"),PLATINUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"platinum_shovel"),PLATINUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"platinum_sword"),PLATINUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"prometheum_axe"),PROMETHEUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"prometheum_hoe"),PROMETHEUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"prometheum_pickaxe"),PROMETHEUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"prometheum_shovel"),PROMETHEUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"prometheum_sword"),PROMETHEUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quadrillum_axe"),QUADRILLUM_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quadrillum_hoe"),QUADRILLUM_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quadrillum_pickaxe"),QUADRILLUM_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quadrillum_shovel"),QUADRILLUM_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quadrillum_sword"),QUADRILLUM_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quicksilver_axe"),QUICKSILVER_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quicksilver_hoe"),QUICKSILVER_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quicksilver_pickaxe"),QUICKSILVER_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quicksilver_shovel"),QUICKSILVER_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"quicksilver_sword"),QUICKSILVER_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"runite_axe"),RUNITE_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"runite_hoe"),RUNITE_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"runite_pickaxe"),RUNITE_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"runite_shovel"),RUNITE_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"runite_sword"),RUNITE_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"silver_axe"),SILVER_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"silver_hoe"),SILVER_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"silver_pickaxe"),SILVER_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"silver_shovel"),SILVER_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"silver_sword"),SILVER_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"slowsilver_axe"),SLOWSILVER_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"slowsilver_hoe"),SLOWSILVER_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"slowsilver_pickaxe"),SLOWSILVER_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"slowsilver_shovel"),SLOWSILVER_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"slowsilver_sword"),SLOWSILVER_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"starrite_axe"),STARRITE_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"starrite_hoe"),STARRITE_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"starrite_pickaxe"),STARRITE_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"starrite_shovel"),STARRITE_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"starrite_sword"),STARRITE_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"steel_axe"),STEEL_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"steel_hoe"),STEEL_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"steel_pickaxe"),STEEL_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"steel_shovel"),STEEL_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"steel_sword"),STEEL_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"stormyx_axe"),STORMYX_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"stormyx_hoe"),STORMYX_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"stormyx_pickaxe"),STORMYX_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"stormyx_shovel"),STORMYX_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"stormyx_sword"),STORMYX_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tantalite_axe"),TANTALITE_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tantalite_hoe"),TANTALITE_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tantalite_pickaxe"),TANTALITE_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tantalite_shovel"),TANTALITE_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tantalite_sword"),TANTALITE_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tin_axe"),TIN_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tin_hoe"),TIN_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tin_pickaxe"),TIN_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tin_shovel"),TIN_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"tin_sword"),TIN_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"truesilver_axe"),TRUESILVER_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"truesilver_hoe"),TRUESILVER_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"truesilver_pickaxe"),TRUESILVER_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"truesilver_shovel"),TRUESILVER_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"truesilver_sword"),TRUESILVER_SWORD);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"ur_axe"),UR_AXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"ur_hoe"),UR_HOE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"ur_pickaxe"),UR_PICKAXE);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"ur_shovel"),UR_SHOVEL);
		Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID,"ur_sword"),UR_SWORD);
}
}