package nourl.mythicmetals.registry;

import net.minecraft.item.Item;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.SwordItem;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;
import nourl.mythicmetals.tools.AxeBase;
import nourl.mythicmetals.tools.HoeBase;
import nourl.mythicmetals.tools.MythicToolMaterials;
import nourl.mythicmetals.tools.PickaxeBase;

public class RegisterTools {
    //SWORDS
    public static final Item ADAMANTITE_SWORD = new SwordItem(MythicToolMaterials.ADAMANTITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_SWORD = new SwordItem(MythicToolMaterials.AETHERIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_SWORD = new SwordItem(MythicToolMaterials.AQUARIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_SWORD = new SwordItem(MythicToolMaterials.BANGLUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_SWORD = new SwordItem(MythicToolMaterials.BRONZE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_SWORD = new SwordItem(MythicToolMaterials.CARMOT, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_SWORD = new SwordItem(MythicToolMaterials.CELESTIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_SWORD = new SwordItem(MythicToolMaterials.COPPER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_SWORD = new SwordItem(MythicToolMaterials.DISCORDIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_SWORD = new SwordItem(MythicToolMaterials.DURASTEEL, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ETHERITE_SWORD = new SwordItem(MythicToolMaterials.ETHERITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_SWORD = new SwordItem(MythicToolMaterials.HALLOWED, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_SWORD = new SwordItem(MythicToolMaterials.KYBER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_SWORD = new SwordItem(MythicToolMaterials.METALLURGIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_SWORD = new SwordItem(MythicToolMaterials.MYTHRIL, 3, -2.2F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_SWORD = new SwordItem(MythicToolMaterials.ORICHALCUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_SWORD = new SwordItem(MythicToolMaterials.OSMIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_SWORD = new SwordItem(MythicToolMaterials.PALLADIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_SWORD = new SwordItem(MythicToolMaterials.PROMETHEUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_SWORD = new SwordItem(MythicToolMaterials.QUADRILLUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_SWORD = new SwordItem(MythicToolMaterials.QUICKSILVER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_SWORD = new SwordItem(MythicToolMaterials.RUNITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_SWORD = new SwordItem(MythicToolMaterials.SILVER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_SWORD = new SwordItem(MythicToolMaterials.STAR_PLATINUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_SWORD = new SwordItem(MythicToolMaterials.STEEL, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_SWORD = new SwordItem(MythicToolMaterials.STORMYX, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    //PICKAXES
    public static final Item ADAMANTITE_PICKAXE = new PickaxeBase(MythicToolMaterials.ADAMANTITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_PICKAXE = new PickaxeBase(MythicToolMaterials.AETHERIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_PICKAXE = new PickaxeBase(MythicToolMaterials.AQUARIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_PICKAXE = new PickaxeBase(MythicToolMaterials.BANGLUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_PICKAXE = new PickaxeBase(MythicToolMaterials.BRONZE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_PICKAXE = new PickaxeBase(MythicToolMaterials.CARMOT, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_PICKAXE = new PickaxeBase(MythicToolMaterials.CELESTIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_PICKAXE = new PickaxeBase(MythicToolMaterials.COPPER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_PICKAXE = new PickaxeBase(MythicToolMaterials.DISCORDIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_PICKAXE = new PickaxeBase(MythicToolMaterials.DURASTEEL, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ETHERITE_PICKAXE = new PickaxeBase(MythicToolMaterials.ETHERITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_PICKAXE = new PickaxeBase(MythicToolMaterials.HALLOWED, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_PICKAXE = new PickaxeBase(MythicToolMaterials.KYBER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_PICKAXE = new PickaxeBase(MythicToolMaterials.METALLURGIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_PICKAXE = new PickaxeBase(MythicToolMaterials.MYTHRIL, 2, -2.6F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_PICKAXE = new PickaxeBase(MythicToolMaterials.ORICHALCUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_PICKAXE = new PickaxeBase(MythicToolMaterials.OSMIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_PICKAXE = new PickaxeBase(MythicToolMaterials.PALLADIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_PICKAXE = new PickaxeBase(MythicToolMaterials.PROMETHEUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_PICKAXE = new PickaxeBase(MythicToolMaterials.QUADRILLUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_PICKAXE = new PickaxeBase(MythicToolMaterials.QUICKSILVER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_PICKAXE = new PickaxeBase(MythicToolMaterials.RUNITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_PICKAXE = new PickaxeBase(MythicToolMaterials.SILVER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_PICKAXE = new PickaxeBase(MythicToolMaterials.STAR_PLATINUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_PICKAXE = new PickaxeBase(MythicToolMaterials.STEEL, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_PICKAXE = new PickaxeBase(MythicToolMaterials.STORMYX, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    //AXES
    public static final Item ADAMANTITE_AXE = new AxeBase(MythicToolMaterials.ADAMANTITE, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_AXE = new AxeBase(MythicToolMaterials.AETHERIUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_AXE = new AxeBase(MythicToolMaterials.AQUARIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_AXE = new AxeBase(MythicToolMaterials.BANGLUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_AXE = new AxeBase(MythicToolMaterials.BRONZE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_AXE = new AxeBase(MythicToolMaterials.CARMOT, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_AXE = new AxeBase(MythicToolMaterials.CELESTIUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_AXE = new AxeBase(MythicToolMaterials.COPPER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_AXE = new AxeBase(MythicToolMaterials.DISCORDIUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_AXE = new AxeBase(MythicToolMaterials.DURASTEEL, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ETHERITE_AXE = new AxeBase(MythicToolMaterials.ETHERITE, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_AXE = new AxeBase(MythicToolMaterials.HALLOWED, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_AXE = new AxeBase(MythicToolMaterials.KYBER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_AXE = new AxeBase(MythicToolMaterials.METALLURGIUM, 5, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_AXE = new AxeBase(MythicToolMaterials.MYTHRIL, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_AXE = new AxeBase(MythicToolMaterials.ORICHALCUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_AXE = new AxeBase(MythicToolMaterials.OSMIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_AXE = new AxeBase(MythicToolMaterials.PALLADIUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_AXE = new AxeBase(MythicToolMaterials.PROMETHEUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_AXE = new AxeBase(MythicToolMaterials.QUADRILLUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_AXE = new AxeBase(MythicToolMaterials.QUICKSILVER, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_AXE = new AxeBase(MythicToolMaterials.RUNITE, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_AXE = new AxeBase(MythicToolMaterials.SILVER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_AXE = new AxeBase(MythicToolMaterials.STAR_PLATINUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_AXE = new AxeBase(MythicToolMaterials.STEEL, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_AXE = new AxeBase(MythicToolMaterials.STORMYX, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    //SHOVELS
    public static final Item ADAMANTITE_SHOVEL = new ShovelItem(MythicToolMaterials.ADAMANTITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_SHOVEL = new ShovelItem(MythicToolMaterials.AETHERIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_SHOVEL = new ShovelItem(MythicToolMaterials.AQUARIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_SHOVEL = new ShovelItem(MythicToolMaterials.BANGLUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_SHOVEL = new ShovelItem(MythicToolMaterials.BRONZE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_SHOVEL = new ShovelItem(MythicToolMaterials.CARMOT, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_SHOVEL = new ShovelItem(MythicToolMaterials.CELESTIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_SHOVEL = new ShovelItem(MythicToolMaterials.COPPER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_SHOVEL = new ShovelItem(MythicToolMaterials.DISCORDIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_SHOVEL = new ShovelItem(MythicToolMaterials.DURASTEEL, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ETHERITE_SHOVEL = new ShovelItem(MythicToolMaterials.ETHERITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_SHOVEL = new ShovelItem(MythicToolMaterials.HALLOWED, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_SHOVEL = new ShovelItem(MythicToolMaterials.KYBER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_SHOVEL = new ShovelItem(MythicToolMaterials.METALLURGIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_SHOVEL = new ShovelItem(MythicToolMaterials.MYTHRIL, 1, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_SHOVEL = new ShovelItem(MythicToolMaterials.ORICHALCUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_SHOVEL = new ShovelItem(MythicToolMaterials.OSMIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_SHOVEL = new ShovelItem(MythicToolMaterials.PALLADIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_SHOVEL = new ShovelItem(MythicToolMaterials.PROMETHEUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_SHOVEL = new ShovelItem(MythicToolMaterials.QUADRILLUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_SHOVEL = new ShovelItem(MythicToolMaterials.QUICKSILVER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_SHOVEL = new ShovelItem(MythicToolMaterials.RUNITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_SHOVEL = new ShovelItem(MythicToolMaterials.SILVER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_SHOVEL = new ShovelItem(MythicToolMaterials.STAR_PLATINUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_SHOVEL = new ShovelItem(MythicToolMaterials.STEEL, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_SHOVEL = new ShovelItem(MythicToolMaterials.STORMYX, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    //HOES
    public static final Item ADAMANTITE_HOE = new HoeBase(MythicToolMaterials.ADAMANTITE, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_HOE = new HoeBase(MythicToolMaterials.AETHERIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_HOE = new HoeBase(MythicToolMaterials.AQUARIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_HOE = new HoeBase(MythicToolMaterials.BANGLUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_HOE = new HoeBase(MythicToolMaterials.BRONZE, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_HOE = new HoeBase(MythicToolMaterials.CARMOT, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_HOE = new HoeBase(MythicToolMaterials.CELESTIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_HOE = new HoeBase(MythicToolMaterials.COPPER, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_HOE = new HoeBase(MythicToolMaterials.DISCORDIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_HOE = new HoeBase(MythicToolMaterials.DURASTEEL, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ETHERITE_HOE = new HoeBase(MythicToolMaterials.ETHERITE, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_HOE = new HoeBase(MythicToolMaterials.HALLOWED, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_HOE = new HoeBase(MythicToolMaterials.KYBER, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_HOE = new HoeBase(MythicToolMaterials.METALLURGIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_HOE = new HoeBase(MythicToolMaterials.MYTHRIL, 0, -2.5F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_HOE = new HoeBase(MythicToolMaterials.ORICHALCUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_HOE = new HoeBase(MythicToolMaterials.OSMIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_HOE = new HoeBase(MythicToolMaterials.PALLADIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_HOE = new HoeBase(MythicToolMaterials.PROMETHEUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_HOE = new HoeBase(MythicToolMaterials.QUADRILLUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_HOE = new HoeBase(MythicToolMaterials.QUICKSILVER, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_HOE = new HoeBase(MythicToolMaterials.RUNITE, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_HOE = new HoeBase(MythicToolMaterials.SILVER, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_HOE = new HoeBase(MythicToolMaterials.STAR_PLATINUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_HOE = new HoeBase(MythicToolMaterials.STEEL, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_HOE = new HoeBase(MythicToolMaterials.STORMYX, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));


    public static void register() {
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_axe"), ADAMANTITE_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_hoe"), ADAMANTITE_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_pickaxe"), ADAMANTITE_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_shovel"), ADAMANTITE_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_sword"), ADAMANTITE_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_axe"), AETHERIUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_hoe"), AETHERIUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_pickaxe"), AETHERIUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_shovel"), AETHERIUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_sword"), AETHERIUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_axe"), AQUARIUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_hoe"), AQUARIUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_pickaxe"), AQUARIUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_shovel"), AQUARIUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_sword"), AQUARIUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_axe"), BANGLUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_hoe"), BANGLUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_pickaxe"), BANGLUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_shovel"), BANGLUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_sword"), BANGLUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_axe"), BRONZE_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_hoe"), BRONZE_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_pickaxe"), BRONZE_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_shovel"), BRONZE_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_sword"), BRONZE_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_axe"), CARMOT_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_hoe"), CARMOT_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_pickaxe"), CARMOT_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_shovel"), CARMOT_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_sword"), CARMOT_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_axe"), CELESTIUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_hoe"), CELESTIUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_pickaxe"), CELESTIUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_shovel"), CELESTIUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_sword"), CELESTIUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_axe"), COPPER_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_hoe"), COPPER_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_pickaxe"), COPPER_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_shovel"), COPPER_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_sword"), COPPER_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_axe"), DISCORDIUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_hoe"), DISCORDIUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_pickaxe"), DISCORDIUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_shovel"), DISCORDIUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_sword"), DISCORDIUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_axe"), DURASTEEL_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_hoe"), DURASTEEL_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_pickaxe"), DURASTEEL_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_shovel"), DURASTEEL_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_sword"), DURASTEEL_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_axe"), ETHERITE_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_hoe"), ETHERITE_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_pickaxe"), ETHERITE_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_shovel"), ETHERITE_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_sword"), ETHERITE_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_axe"), KYBER_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_hoe"), KYBER_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_pickaxe"), KYBER_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_shovel"), KYBER_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_sword"), KYBER_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_axe"), HALLOWED_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_hoe"), HALLOWED_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_pickaxe"), HALLOWED_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_shovel"), HALLOWED_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_sword"), HALLOWED_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_axe"), METALLURGIUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_hoe"), METALLURGIUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_pickaxe"), METALLURGIUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_shovel"), METALLURGIUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_sword"), METALLURGIUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_axe"), MYTHRIL_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_hoe"), MYTHRIL_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_pickaxe"), MYTHRIL_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_shovel"), MYTHRIL_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_sword"), MYTHRIL_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_axe"), ORICHALCUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_hoe"), ORICHALCUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_pickaxe"), ORICHALCUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_shovel"), ORICHALCUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_sword"), ORICHALCUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_axe"), OSMIUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_hoe"), OSMIUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_pickaxe"), OSMIUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_shovel"), OSMIUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_sword"), OSMIUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_axe"), PALLADIUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_hoe"), PALLADIUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_pickaxe"), PALLADIUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_shovel"), PALLADIUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_sword"), PALLADIUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_axe"), PROMETHEUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_hoe"), PROMETHEUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_pickaxe"), PROMETHEUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_shovel"), PROMETHEUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_sword"), PROMETHEUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_axe"), QUADRILLUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_hoe"), QUADRILLUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_pickaxe"), QUADRILLUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_shovel"), QUADRILLUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_sword"), QUADRILLUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_axe"), QUICKSILVER_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_hoe"), QUICKSILVER_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_pickaxe"), QUICKSILVER_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_shovel"), QUICKSILVER_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_sword"), QUICKSILVER_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_axe"), RUNITE_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_hoe"), RUNITE_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_pickaxe"), RUNITE_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_shovel"), RUNITE_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_sword"), RUNITE_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_axe"), SILVER_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_hoe"), SILVER_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_pickaxe"), SILVER_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_shovel"), SILVER_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_sword"), SILVER_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_axe"), STAR_PLATINUM_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_hoe"), STAR_PLATINUM_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_pickaxe"), STAR_PLATINUM_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_shovel"), STAR_PLATINUM_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_sword"), STAR_PLATINUM_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_axe"), STEEL_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_hoe"), STEEL_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_pickaxe"), STEEL_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_shovel"), STEEL_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_sword"), STEEL_SWORD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_axe"), STORMYX_AXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_hoe"), STORMYX_HOE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_pickaxe"), STORMYX_PICKAXE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_shovel"), STORMYX_SHOVEL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_sword"), STORMYX_SWORD);
    }
}