package nourl.mythicmetals.registry;

import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.ArmorItem;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;
//import nourl.mythicmetals.armor.HallowedArmor;
//import nourl.mythicmetals.armor.MetallurgiumArmor;
import nourl.mythicmetals.armor.MythicArmorMaterials;

public class RegisterArmor {
    public static final Item ADAMANTITE_HELMET = new ArmorItem(MythicArmorMaterials.ADAMANTITE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ADAMANTITE_CHESTPLATE = new ArmorItem(MythicArmorMaterials.ADAMANTITE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ADAMANTITE_LEGGINGS = new ArmorItem(MythicArmorMaterials.ADAMANTITE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ADAMANTITE_BOOTS = new ArmorItem(MythicArmorMaterials.ADAMANTITE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_HELMET = new ArmorItem(MythicArmorMaterials.AETHERIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.AETHERIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.AETHERIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_BOOTS = new ArmorItem(MythicArmorMaterials.AETHERIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_HELMET = new ArmorItem(MythicArmorMaterials.AQUARIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.AQUARIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.AQUARIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_BOOTS = new ArmorItem(MythicArmorMaterials.AQUARIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_HELMET = new ArmorItem(MythicArmorMaterials.BANGLUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.BANGLUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.BANGLUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_BOOTS = new ArmorItem(MythicArmorMaterials.BANGLUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_HELMET = new ArmorItem(MythicArmorMaterials.BRONZE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_CHESTPLATE = new ArmorItem(MythicArmorMaterials.BRONZE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_LEGGINGS = new ArmorItem(MythicArmorMaterials.BRONZE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_BOOTS = new ArmorItem(MythicArmorMaterials.BRONZE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_HELMET = new ArmorItem(MythicArmorMaterials.CARMOT, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_CHESTPLATE = new ArmorItem(MythicArmorMaterials.CARMOT, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_LEGGINGS = new ArmorItem(MythicArmorMaterials.CARMOT, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_BOOTS = new ArmorItem(MythicArmorMaterials.CARMOT, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_HELMET = new ArmorItem(MythicArmorMaterials.CELESTIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.CELESTIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.CELESTIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_BOOTS = new ArmorItem(MythicArmorMaterials.CELESTIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_HELMET = new ArmorItem(MythicArmorMaterials.COPPER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_CHESTPLATE = new ArmorItem(MythicArmorMaterials.COPPER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_LEGGINGS = new ArmorItem(MythicArmorMaterials.COPPER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_BOOTS = new ArmorItem(MythicArmorMaterials.COPPER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_HELMET = new ArmorItem(MythicArmorMaterials.DISCORDIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.DISCORDIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.DISCORDIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_BOOTS = new ArmorItem(MythicArmorMaterials.DISCORDIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_HELMET = new ArmorItem(MythicArmorMaterials.DURASTEEL, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_CHESTPLATE = new ArmorItem(MythicArmorMaterials.DURASTEEL, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_LEGGINGS = new ArmorItem(MythicArmorMaterials.DURASTEEL, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_BOOTS = new ArmorItem(MythicArmorMaterials.DURASTEEL, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_HELMET = new ArmorItem(MythicArmorMaterials.ETHERITE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_CHESTPLATE = new ArmorItem(MythicArmorMaterials.ETHERITE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_LEGGINGS = new ArmorItem(MythicArmorMaterials.ETHERITE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_BOOTS = new ArmorItem(MythicArmorMaterials.ETHERITE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_HELMET = new ArmorItem(MythicArmorMaterials.HALLOWED, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_CHESTPLATE = new ArmorItem(MythicArmorMaterials.HALLOWED, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_LEGGINGS = new ArmorItem(MythicArmorMaterials.HALLOWED, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_BOOTS = new ArmorItem(MythicArmorMaterials.HALLOWED, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_HELMET = new ArmorItem(MythicArmorMaterials.KYBER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_CHESTPLATE = new ArmorItem(MythicArmorMaterials.KYBER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_LEGGINGS = new ArmorItem(MythicArmorMaterials.KYBER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_BOOTS = new ArmorItem(MythicArmorMaterials.KYBER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item METALLURGIUM_HELMET = new ArmorItem(MythicArmorMaterials.METALLURGIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item METALLURGIUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.METALLURGIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item METALLURGIUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.METALLURGIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item METALLURGIUM_BOOTS = new ArmorItem(MythicArmorMaterials.METALLURGIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item MIDAS_GOLD_HELMET = new ArmorItem(MythicArmorMaterials.MIDAS_GOLD, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MIDAS_GOLD_CHESTPLATE = new ArmorItem(MythicArmorMaterials.MIDAS_GOLD, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MIDAS_GOLD_LEGGINGS = new ArmorItem(MythicArmorMaterials.MIDAS_GOLD, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MIDAS_GOLD_BOOTS = new ArmorItem(MythicArmorMaterials.MIDAS_GOLD, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_HELMET = new ArmorItem(MythicArmorMaterials.MYTHRIL, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_CHESTPLATE = new ArmorItem(MythicArmorMaterials.MYTHRIL, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_LEGGINGS = new ArmorItem(MythicArmorMaterials.MYTHRIL, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_BOOTS = new ArmorItem(MythicArmorMaterials.MYTHRIL, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_HELMET = new ArmorItem(MythicArmorMaterials.ORICHALCUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.ORICHALCUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.ORICHALCUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_BOOTS = new ArmorItem(MythicArmorMaterials.ORICHALCUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_HELMET = new ArmorItem(MythicArmorMaterials.OSMIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.OSMIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.OSMIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_BOOTS = new ArmorItem(MythicArmorMaterials.OSMIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PALLADIUM_HELMET = new ArmorItem(MythicArmorMaterials.PALLADIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PALLADIUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.PALLADIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PALLADIUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.PALLADIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PALLADIUM_BOOTS = new ArmorItem(MythicArmorMaterials.PALLADIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PROMETHEUM_HELMET = new ArmorItem(MythicArmorMaterials.PROMETHEUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PROMETHEUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.PROMETHEUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PROMETHEUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.PROMETHEUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PROMETHEUM_BOOTS = new ArmorItem(MythicArmorMaterials.PROMETHEUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_HELMET = new ArmorItem(MythicArmorMaterials.QUICKSILVER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_CHESTPLATE = new ArmorItem(MythicArmorMaterials.QUICKSILVER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_LEGGINGS = new ArmorItem(MythicArmorMaterials.QUICKSILVER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_BOOTS = new ArmorItem(MythicArmorMaterials.QUICKSILVER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_HELMET = new ArmorItem(MythicArmorMaterials.RUNITE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_CHESTPLATE = new ArmorItem(MythicArmorMaterials.RUNITE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_LEGGINGS = new ArmorItem(MythicArmorMaterials.RUNITE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_BOOTS = new ArmorItem(MythicArmorMaterials.RUNITE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_HELMET = new ArmorItem(MythicArmorMaterials.SILVER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_CHESTPLATE = new ArmorItem(MythicArmorMaterials.SILVER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_LEGGINGS = new ArmorItem(MythicArmorMaterials.SILVER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_BOOTS = new ArmorItem(MythicArmorMaterials.SILVER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_HELMET = new ArmorItem(MythicArmorMaterials.STAR_PLATINUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_CHESTPLATE = new ArmorItem(MythicArmorMaterials.STAR_PLATINUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_LEGGINGS = new ArmorItem(MythicArmorMaterials.STAR_PLATINUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_BOOTS = new ArmorItem(MythicArmorMaterials.STAR_PLATINUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_HELMET = new ArmorItem(MythicArmorMaterials.STEEL, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_CHESTPLATE = new ArmorItem(MythicArmorMaterials.STEEL, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_LEGGINGS = new ArmorItem(MythicArmorMaterials.STEEL, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_BOOTS = new ArmorItem(MythicArmorMaterials.STEEL, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_HELMET = new ArmorItem(MythicArmorMaterials.STORMYX, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_CHESTPLATE = new ArmorItem(MythicArmorMaterials.STORMYX, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_LEGGINGS = new ArmorItem(MythicArmorMaterials.STORMYX, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_BOOTS = new ArmorItem(MythicArmorMaterials.STORMYX, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));

    public static void register() {
        //Register Armor
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_helmet"), ADAMANTITE_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_chestplate"), ADAMANTITE_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_leggings"), ADAMANTITE_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_boots"), ADAMANTITE_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_helmet"), AETHERIUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_chestplate"), AETHERIUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_leggings"), AETHERIUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_boots"), AETHERIUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_helmet"), AQUARIUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_chestplate"), AQUARIUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_leggings"), AQUARIUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_boots"), AQUARIUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_helmet"), BANGLUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_chestplate"), BANGLUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_leggings"), BANGLUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_boots"), BANGLUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_helmet"), BRONZE_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_chestplate"), BRONZE_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_leggings"), BRONZE_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_boots"), BRONZE_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_helmet"), CARMOT_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_chestplate"), CARMOT_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_leggings"), CARMOT_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_boots"), CARMOT_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_helmet"), CELESTIUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_chestplate"), CELESTIUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_leggings"), CELESTIUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_boots"), CELESTIUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_helmet"), COPPER_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_chestplate"), COPPER_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_leggings"), COPPER_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_boots"), COPPER_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_helmet"), DISCORDIUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_chestplate"), DISCORDIUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_leggings"), DISCORDIUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_boots"), DISCORDIUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_helmet"), DURASTEEL_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_chestplate"), DURASTEEL_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_leggings"), DURASTEEL_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_boots"), DURASTEEL_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_helmet"), ETHERITE_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_chestplate"), ETHERITE_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_leggings"), ETHERITE_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_boots"), ETHERITE_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_helmet"), HALLOWED_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_chestplate"), HALLOWED_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_leggings"), HALLOWED_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_boots"), HALLOWED_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_helmet"), KYBER_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_chestplate"), KYBER_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_leggings"), KYBER_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_boots"), KYBER_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_helmet"), METALLURGIUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_chestplate"), METALLURGIUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_leggings"), METALLURGIUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_boots"), METALLURGIUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_helmet"), MIDAS_GOLD_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_chestplate"), MIDAS_GOLD_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_leggings"), MIDAS_GOLD_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_boots"), MIDAS_GOLD_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_helmet"), MYTHRIL_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_chestplate"), MYTHRIL_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_leggings"), MYTHRIL_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_boots"), MYTHRIL_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_helmet"), ORICHALCUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_chestplate"), ORICHALCUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_leggings"), ORICHALCUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_boots"), ORICHALCUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_helmet"), OSMIUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_chestplate"), OSMIUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_leggings"), OSMIUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_boots"), OSMIUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_helmet"), PALLADIUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_chestplate"), PALLADIUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_leggings"), PALLADIUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_boots"), PALLADIUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_helmet"), PROMETHEUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_chestplate"), PROMETHEUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_leggings"), PROMETHEUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_boots"), PROMETHEUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_helmet"), QUICKSILVER_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_chestplate"), QUICKSILVER_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_leggings"), QUICKSILVER_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_boots"), QUICKSILVER_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_helmet"), RUNITE_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_chestplate"), RUNITE_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_leggings"), RUNITE_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_boots"), RUNITE_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_helmet"), SILVER_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_chestplate"), SILVER_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_leggings"), SILVER_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_boots"), SILVER_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_helmet"), STAR_PLATINUM_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_chestplate"), STAR_PLATINUM_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_leggings"), STAR_PLATINUM_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "star_platinum_boots"), STAR_PLATINUM_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_helmet"), STEEL_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_chestplate"), STEEL_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_leggings"), STEEL_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_boots"), STEEL_BOOTS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_helmet"), STORMYX_HELMET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_chestplate"), STORMYX_CHESTPLATE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_leggings"), STORMYX_LEGGINGS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_boots"), STORMYX_BOOTS);

    }
}
