package nourl.mythicmetals.registry;

import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.ArmorItem;
import net.minecraft.item.Item;
import nourl.mythicmetals.MythicMetals;
import nourl.mythicmetals.armor.ArmorMaterials;

public class RegisterArmor {
    public static final Item ADAMANTITE_HELMET = new ArmorItem(ArmorMaterials.ADAMANTITE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ADAMANTITE_CHESTPLATE = new ArmorItem(ArmorMaterials.ADAMANTITE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ADAMANTITE_LEGGINGS = new ArmorItem(ArmorMaterials.ADAMANTITE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ADAMANTITE_BOOTS = new ArmorItem(ArmorMaterials.ADAMANTITE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_HELMET = new ArmorItem(ArmorMaterials.AETHERIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_CHESTPLATE = new ArmorItem(ArmorMaterials.AETHERIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_LEGGINGS = new ArmorItem(ArmorMaterials.AETHERIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AETHERIUM_BOOTS = new ArmorItem(ArmorMaterials.AETHERIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_HELMET = new ArmorItem(ArmorMaterials.AQUARIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_CHESTPLATE = new ArmorItem(ArmorMaterials.AQUARIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_LEGGINGS = new ArmorItem(ArmorMaterials.AQUARIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item AQUARIUM_BOOTS = new ArmorItem(ArmorMaterials.AQUARIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_HELMET = new ArmorItem(ArmorMaterials.BANGLUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_CHESTPLATE = new ArmorItem(ArmorMaterials.BANGLUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_LEGGINGS = new ArmorItem(ArmorMaterials.BANGLUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BANGLUM_BOOTS = new ArmorItem(ArmorMaterials.BANGLUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_HELMET = new ArmorItem(ArmorMaterials.BRONZE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_CHESTPLATE = new ArmorItem(ArmorMaterials.BRONZE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_LEGGINGS = new ArmorItem(ArmorMaterials.BRONZE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item BRONZE_BOOTS = new ArmorItem(ArmorMaterials.BRONZE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_HELMET = new ArmorItem(ArmorMaterials.CARMOT, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_CHESTPLATE = new ArmorItem(ArmorMaterials.CARMOT, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_LEGGINGS = new ArmorItem(ArmorMaterials.CARMOT, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CARMOT_BOOTS = new ArmorItem(ArmorMaterials.CARMOT, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_HELMET = new ArmorItem(ArmorMaterials.CELESTIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_CHESTPLATE = new ArmorItem(ArmorMaterials.CELESTIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_LEGGINGS = new ArmorItem(ArmorMaterials.CELESTIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item CELESTIUM_BOOTS = new ArmorItem(ArmorMaterials.CELESTIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_HELMET = new ArmorItem(ArmorMaterials.COPPER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_CHESTPLATE = new ArmorItem(ArmorMaterials.COPPER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_LEGGINGS = new ArmorItem(ArmorMaterials.COPPER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item COPPER_BOOTS = new ArmorItem(ArmorMaterials.COPPER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_HELMET = new ArmorItem(ArmorMaterials.DISCORDIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_CHESTPLATE = new ArmorItem(ArmorMaterials.DISCORDIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_LEGGINGS = new ArmorItem(ArmorMaterials.DISCORDIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DISCORDIUM_BOOTS = new ArmorItem(ArmorMaterials.DISCORDIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_HELMET = new ArmorItem(ArmorMaterials.DURASTEEL, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_CHESTPLATE = new ArmorItem(ArmorMaterials.DURASTEEL, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_LEGGINGS = new ArmorItem(ArmorMaterials.DURASTEEL, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item DURASTEEL_BOOTS = new ArmorItem(ArmorMaterials.DURASTEEL, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_HELMET = new ArmorItem(ArmorMaterials.ETHERITE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_CHESTPLATE = new ArmorItem(ArmorMaterials.ETHERITE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_LEGGINGS = new ArmorItem(ArmorMaterials.ETHERITE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ETHERITE_BOOTS = new ArmorItem(ArmorMaterials.ETHERITE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_HELMET = new ArmorItem(ArmorMaterials.HALLOWED, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_CHESTPLATE = new ArmorItem(ArmorMaterials.HALLOWED, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_LEGGINGS = new ArmorItem(ArmorMaterials.HALLOWED, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item HALLOWED_BOOTS = new ArmorItem(ArmorMaterials.HALLOWED, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_HELMET = new ArmorItem(ArmorMaterials.KYBER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_CHESTPLATE = new ArmorItem(ArmorMaterials.KYBER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_LEGGINGS = new ArmorItem(ArmorMaterials.KYBER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item KYBER_BOOTS = new ArmorItem(ArmorMaterials.KYBER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item METALLURGIUM_HELMET = new ArmorItem(ArmorMaterials.METALLURGIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item METALLURGIUM_CHESTPLATE = new ArmorItem(ArmorMaterials.METALLURGIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item METALLURGIUM_LEGGINGS = new ArmorItem(ArmorMaterials.METALLURGIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item METALLURGIUM_BOOTS = new ArmorItem(ArmorMaterials.METALLURGIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof()));
    public static final Item MIDAS_GOLD_HELMET = new ArmorItem(ArmorMaterials.MIDAS_GOLD, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MIDAS_GOLD_CHESTPLATE = new ArmorItem(ArmorMaterials.MIDAS_GOLD, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MIDAS_GOLD_LEGGINGS = new ArmorItem(ArmorMaterials.MIDAS_GOLD, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MIDAS_GOLD_BOOTS = new ArmorItem(ArmorMaterials.MIDAS_GOLD, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_HELMET = new ArmorItem(ArmorMaterials.MYTHRIL, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_CHESTPLATE = new ArmorItem(ArmorMaterials.MYTHRIL, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_LEGGINGS = new ArmorItem(ArmorMaterials.MYTHRIL, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item MYTHRIL_BOOTS = new ArmorItem(ArmorMaterials.MYTHRIL, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_HELMET = new ArmorItem(ArmorMaterials.ORICHALCUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_CHESTPLATE = new ArmorItem(ArmorMaterials.ORICHALCUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_LEGGINGS = new ArmorItem(ArmorMaterials.ORICHALCUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item ORICHALCUM_BOOTS = new ArmorItem(ArmorMaterials.ORICHALCUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_HELMET = new ArmorItem(ArmorMaterials.OSMIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_CHESTPLATE = new ArmorItem(ArmorMaterials.OSMIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_LEGGINGS = new ArmorItem(ArmorMaterials.OSMIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item OSMIUM_BOOTS = new ArmorItem(ArmorMaterials.OSMIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PALLADIUM_HELMET = new ArmorItem(ArmorMaterials.PALLADIUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)).fireproof());
    public static final Item PALLADIUM_CHESTPLATE = new ArmorItem(ArmorMaterials.PALLADIUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)).fireproof());
    public static final Item PALLADIUM_LEGGINGS = new ArmorItem(ArmorMaterials.PALLADIUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)).fireproof());
    public static final Item PALLADIUM_BOOTS = new ArmorItem(ArmorMaterials.PALLADIUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)).fireproof());
    public static final Item PROMETHEUM_HELMET = new ArmorItem(ArmorMaterials.PROMETHEUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PROMETHEUM_CHESTPLATE = new ArmorItem(ArmorMaterials.PROMETHEUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PROMETHEUM_LEGGINGS = new ArmorItem(ArmorMaterials.PROMETHEUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item PROMETHEUM_BOOTS = new ArmorItem(ArmorMaterials.PROMETHEUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_HELMET = new ArmorItem(ArmorMaterials.QUICKSILVER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_CHESTPLATE = new ArmorItem(ArmorMaterials.QUICKSILVER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_LEGGINGS = new ArmorItem(ArmorMaterials.QUICKSILVER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item QUICKSILVER_BOOTS = new ArmorItem(ArmorMaterials.QUICKSILVER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_HELMET = new ArmorItem(ArmorMaterials.RUNITE, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_CHESTPLATE = new ArmorItem(ArmorMaterials.RUNITE, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_LEGGINGS = new ArmorItem(ArmorMaterials.RUNITE, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item RUNITE_BOOTS = new ArmorItem(ArmorMaterials.RUNITE, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_HELMET = new ArmorItem(ArmorMaterials.SILVER, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_CHESTPLATE = new ArmorItem(ArmorMaterials.SILVER, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_LEGGINGS = new ArmorItem(ArmorMaterials.SILVER, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item SILVER_BOOTS = new ArmorItem(ArmorMaterials.SILVER, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_HELMET = new ArmorItem(ArmorMaterials.STAR_PLATINUM, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_CHESTPLATE = new ArmorItem(ArmorMaterials.STAR_PLATINUM, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_LEGGINGS = new ArmorItem(ArmorMaterials.STAR_PLATINUM, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STAR_PLATINUM_BOOTS = new ArmorItem(ArmorMaterials.STAR_PLATINUM, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_HELMET = new ArmorItem(ArmorMaterials.STEEL, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_CHESTPLATE = new ArmorItem(ArmorMaterials.STEEL, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_LEGGINGS = new ArmorItem(ArmorMaterials.STEEL, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STEEL_BOOTS = new ArmorItem(ArmorMaterials.STEEL, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_HELMET = new ArmorItem(ArmorMaterials.STORMYX, EquipmentSlot.HEAD, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_CHESTPLATE = new ArmorItem(ArmorMaterials.STORMYX, EquipmentSlot.CHEST, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_LEGGINGS = new ArmorItem(ArmorMaterials.STORMYX, EquipmentSlot.LEGS, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));
    public static final Item STORMYX_BOOTS = new ArmorItem(ArmorMaterials.STORMYX, EquipmentSlot.FEET, (new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR)));

    public static void register() {
        //Register Armor
        RegistryHelper.item( "adamantite_helmet", ADAMANTITE_HELMET);
        RegistryHelper.item( "adamantite_chestplate", ADAMANTITE_CHESTPLATE);
        RegistryHelper.item( "adamantite_leggings", ADAMANTITE_LEGGINGS);
        RegistryHelper.item( "adamantite_boots", ADAMANTITE_BOOTS);
        RegistryHelper.item( "aetherium_helmet", AETHERIUM_HELMET);
        RegistryHelper.item( "aetherium_chestplate", AETHERIUM_CHESTPLATE);
        RegistryHelper.item( "aetherium_leggings", AETHERIUM_LEGGINGS);
        RegistryHelper.item( "aetherium_boots", AETHERIUM_BOOTS);
        RegistryHelper.item( "aquarium_helmet", AQUARIUM_HELMET);
        RegistryHelper.item( "aquarium_chestplate", AQUARIUM_CHESTPLATE);
        RegistryHelper.item( "aquarium_leggings", AQUARIUM_LEGGINGS);
        RegistryHelper.item( "aquarium_boots", AQUARIUM_BOOTS);
        RegistryHelper.item( "banglum_helmet", BANGLUM_HELMET);
        RegistryHelper.item( "banglum_chestplate", BANGLUM_CHESTPLATE);
        RegistryHelper.item( "banglum_leggings", BANGLUM_LEGGINGS);
        RegistryHelper.item( "banglum_boots", BANGLUM_BOOTS);
        RegistryHelper.item( "bronze_helmet", BRONZE_HELMET);
        RegistryHelper.item( "bronze_chestplate", BRONZE_CHESTPLATE);
        RegistryHelper.item( "bronze_leggings", BRONZE_LEGGINGS);
        RegistryHelper.item( "bronze_boots", BRONZE_BOOTS);
        RegistryHelper.item( "carmot_helmet", CARMOT_HELMET);
        RegistryHelper.item( "carmot_chestplate", CARMOT_CHESTPLATE);
        RegistryHelper.item( "carmot_leggings", CARMOT_LEGGINGS);
        RegistryHelper.item( "carmot_boots", CARMOT_BOOTS);
        RegistryHelper.item( "celestium_helmet", CELESTIUM_HELMET);
        RegistryHelper.item( "celestium_chestplate", CELESTIUM_CHESTPLATE);
        RegistryHelper.item( "celestium_leggings", CELESTIUM_LEGGINGS);
        RegistryHelper.item( "celestium_boots", CELESTIUM_BOOTS);
        RegistryHelper.item( "copper_helmet", COPPER_HELMET);
        RegistryHelper.item( "copper_chestplate", COPPER_CHESTPLATE);
        RegistryHelper.item( "copper_leggings", COPPER_LEGGINGS);
        RegistryHelper.item( "copper_boots", COPPER_BOOTS);
        RegistryHelper.item( "discordium_helmet", DISCORDIUM_HELMET);
        RegistryHelper.item( "discordium_chestplate", DISCORDIUM_CHESTPLATE);
        RegistryHelper.item( "discordium_leggings", DISCORDIUM_LEGGINGS);
        RegistryHelper.item( "discordium_boots", DISCORDIUM_BOOTS);
        RegistryHelper.item( "durasteel_helmet", DURASTEEL_HELMET);
        RegistryHelper.item( "durasteel_chestplate", DURASTEEL_CHESTPLATE);
        RegistryHelper.item( "durasteel_leggings", DURASTEEL_LEGGINGS);
        RegistryHelper.item( "durasteel_boots", DURASTEEL_BOOTS);
        RegistryHelper.item( "etherite_helmet", ETHERITE_HELMET);
        RegistryHelper.item( "etherite_chestplate", ETHERITE_CHESTPLATE);
        RegistryHelper.item( "etherite_leggings", ETHERITE_LEGGINGS);
        RegistryHelper.item( "etherite_boots", ETHERITE_BOOTS);
        RegistryHelper.item( "hallowed_helmet", HALLOWED_HELMET);
        RegistryHelper.item( "hallowed_chestplate", HALLOWED_CHESTPLATE);
        RegistryHelper.item( "hallowed_leggings", HALLOWED_LEGGINGS);
        RegistryHelper.item( "hallowed_boots", HALLOWED_BOOTS);
        RegistryHelper.item( "kyber_helmet", KYBER_HELMET);
        RegistryHelper.item( "kyber_chestplate", KYBER_CHESTPLATE);
        RegistryHelper.item( "kyber_leggings", KYBER_LEGGINGS);
        RegistryHelper.item( "kyber_boots", KYBER_BOOTS);
        RegistryHelper.item( "metallurgium_helmet", METALLURGIUM_HELMET);
        RegistryHelper.item( "metallurgium_chestplate", METALLURGIUM_CHESTPLATE);
        RegistryHelper.item( "metallurgium_leggings", METALLURGIUM_LEGGINGS);
        RegistryHelper.item( "metallurgium_boots", METALLURGIUM_BOOTS);
        RegistryHelper.item( "midas_gold_helmet", MIDAS_GOLD_HELMET);
        RegistryHelper.item( "midas_gold_chestplate", MIDAS_GOLD_CHESTPLATE);
        RegistryHelper.item( "midas_gold_leggings", MIDAS_GOLD_LEGGINGS);
        RegistryHelper.item( "midas_gold_boots", MIDAS_GOLD_BOOTS);
        RegistryHelper.item( "mythril_helmet", MYTHRIL_HELMET);
        RegistryHelper.item( "mythril_chestplate", MYTHRIL_CHESTPLATE);
        RegistryHelper.item( "mythril_leggings", MYTHRIL_LEGGINGS);
        RegistryHelper.item( "mythril_boots", MYTHRIL_BOOTS);
        RegistryHelper.item( "orichalcum_helmet", ORICHALCUM_HELMET);
        RegistryHelper.item( "orichalcum_chestplate", ORICHALCUM_CHESTPLATE);
        RegistryHelper.item( "orichalcum_leggings", ORICHALCUM_LEGGINGS);
        RegistryHelper.item( "orichalcum_boots", ORICHALCUM_BOOTS);
        RegistryHelper.item( "osmium_helmet", OSMIUM_HELMET);
        RegistryHelper.item( "osmium_chestplate", OSMIUM_CHESTPLATE);
        RegistryHelper.item( "osmium_leggings", OSMIUM_LEGGINGS);
        RegistryHelper.item( "osmium_boots", OSMIUM_BOOTS);
        RegistryHelper.item( "palladium_helmet", PALLADIUM_HELMET);
        RegistryHelper.item( "palladium_chestplate", PALLADIUM_CHESTPLATE);
        RegistryHelper.item( "palladium_leggings", PALLADIUM_LEGGINGS);
        RegistryHelper.item( "palladium_boots", PALLADIUM_BOOTS);
        RegistryHelper.item( "prometheum_helmet", PROMETHEUM_HELMET);
        RegistryHelper.item( "prometheum_chestplate", PROMETHEUM_CHESTPLATE);
        RegistryHelper.item( "prometheum_leggings", PROMETHEUM_LEGGINGS);
        RegistryHelper.item( "prometheum_boots", PROMETHEUM_BOOTS);
        RegistryHelper.item( "quicksilver_helmet", QUICKSILVER_HELMET);
        RegistryHelper.item( "quicksilver_chestplate", QUICKSILVER_CHESTPLATE);
        RegistryHelper.item( "quicksilver_leggings", QUICKSILVER_LEGGINGS);
        RegistryHelper.item( "quicksilver_boots", QUICKSILVER_BOOTS);
        RegistryHelper.item( "runite_helmet", RUNITE_HELMET);
        RegistryHelper.item( "runite_chestplate", RUNITE_CHESTPLATE);
        RegistryHelper.item( "runite_leggings", RUNITE_LEGGINGS);
        RegistryHelper.item( "runite_boots", RUNITE_BOOTS);
        RegistryHelper.item( "silver_helmet", SILVER_HELMET);
        RegistryHelper.item( "silver_chestplate", SILVER_CHESTPLATE);
        RegistryHelper.item( "silver_leggings", SILVER_LEGGINGS);
        RegistryHelper.item( "silver_boots", SILVER_BOOTS);
        RegistryHelper.item( "star_platinum_helmet", STAR_PLATINUM_HELMET);
        RegistryHelper.item( "star_platinum_chestplate", STAR_PLATINUM_CHESTPLATE);
        RegistryHelper.item( "star_platinum_leggings", STAR_PLATINUM_LEGGINGS);
        RegistryHelper.item( "star_platinum_boots", STAR_PLATINUM_BOOTS);
        RegistryHelper.item( "steel_helmet", STEEL_HELMET);
        RegistryHelper.item( "steel_chestplate", STEEL_CHESTPLATE);
        RegistryHelper.item( "steel_leggings", STEEL_LEGGINGS);
        RegistryHelper.item( "steel_boots", STEEL_BOOTS);
        RegistryHelper.item( "stormyx_helmet", STORMYX_HELMET);
        RegistryHelper.item( "stormyx_chestplate", STORMYX_CHESTPLATE);
        RegistryHelper.item( "stormyx_leggings", STORMYX_LEGGINGS);
        RegistryHelper.item( "stormyx_boots", STORMYX_BOOTS);

    }

}
