package nourl.mythicmetals.registry;

import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.ArmorItem;
import net.minecraft.item.ArmorMaterial;
import net.minecraft.item.Item;
import nourl.mythicmetals.MythicMetals;
import nourl.mythicmetals.armor.ArmorMaterials;
import nourl.mythicmetals.armor.ArmorSet;

import static net.minecraft.entity.EquipmentSlot.*;
import static nourl.mythicmetals.armor.ArmorMaterials.*;

public class RegisterArmor {

    public static final ArmorSet ADAMANTITE = new ArmorSet(ArmorMaterials.ADAMANTITE);
    public static final ArmorSet METALLURGIUM = new ArmorSet(ArmorMaterials.METALLURGIUM, Item.Settings::fireproof);

    public static final Item AETHERIUM_HELMET = baseArmorItem(AETHERIUM, HEAD);
    public static final Item AETHERIUM_CHESTPLATE = baseArmorItem(AETHERIUM, CHEST);
    public static final Item AETHERIUM_LEGGINGS = baseArmorItem(AETHERIUM, LEGS);
    public static final Item AETHERIUM_BOOTS = baseArmorItem(AETHERIUM, FEET);
    public static final Item AQUARIUM_HELMET = baseArmorItem(AQUARIUM, HEAD);
    public static final Item AQUARIUM_CHESTPLATE = baseArmorItem(AQUARIUM, CHEST);
    public static final Item AQUARIUM_LEGGINGS = baseArmorItem(AQUARIUM, LEGS);
    public static final Item AQUARIUM_BOOTS = baseArmorItem(AQUARIUM, FEET);
    public static final Item BANGLUM_HELMET = baseArmorItem(BANGLUM, HEAD);
    public static final Item BANGLUM_CHESTPLATE = baseArmorItem(BANGLUM, CHEST);
    public static final Item BANGLUM_LEGGINGS = baseArmorItem(BANGLUM, LEGS);
    public static final Item BANGLUM_BOOTS = baseArmorItem(BANGLUM, FEET);
    public static final Item BRONZE_HELMET = baseArmorItem(BRONZE, HEAD);
    public static final Item BRONZE_CHESTPLATE = baseArmorItem(BRONZE, CHEST);
    public static final Item BRONZE_LEGGINGS = baseArmorItem(BRONZE, LEGS);
    public static final Item BRONZE_BOOTS = baseArmorItem(BRONZE, FEET);
    public static final Item CARMOT_HELMET = baseArmorItem(CARMOT, HEAD);
    public static final Item CARMOT_CHESTPLATE = baseArmorItem(CARMOT, CHEST);
    public static final Item CARMOT_LEGGINGS = baseArmorItem(CARMOT, LEGS);
    public static final Item CARMOT_BOOTS = baseArmorItem(CARMOT, FEET);
    public static final Item CELESTIUM_HELMET = baseArmorItem(CELESTIUM, HEAD);
    public static final Item CELESTIUM_CHESTPLATE = baseArmorItem(CELESTIUM, CHEST);
    public static final Item CELESTIUM_LEGGINGS = baseArmorItem(CELESTIUM, LEGS);
    public static final Item CELESTIUM_BOOTS = baseArmorItem(CELESTIUM, FEET);
    public static final Item COPPER_HELMET = baseArmorItem(COPPER, HEAD);
    public static final Item COPPER_CHESTPLATE = baseArmorItem(COPPER, CHEST);
    public static final Item COPPER_LEGGINGS = baseArmorItem(COPPER, LEGS);
    public static final Item COPPER_BOOTS = baseArmorItem(COPPER, FEET);
    public static final Item DISCORDIUM_HELMET = baseArmorItem(DISCORDIUM, HEAD);
    public static final Item DISCORDIUM_CHESTPLATE = baseArmorItem(DISCORDIUM, CHEST);
    public static final Item DISCORDIUM_LEGGINGS = baseArmorItem(DISCORDIUM, LEGS);
    public static final Item DISCORDIUM_BOOTS = baseArmorItem(DISCORDIUM, FEET);
    public static final Item DURASTEEL_HELMET = baseArmorItem(DURASTEEL, HEAD);
    public static final Item DURASTEEL_CHESTPLATE = baseArmorItem(DURASTEEL, CHEST);
    public static final Item DURASTEEL_LEGGINGS = baseArmorItem(DURASTEEL, LEGS);
    public static final Item DURASTEEL_BOOTS = baseArmorItem(DURASTEEL, FEET);
    public static final Item ETHERITE_HELMET = baseArmorItem(ETHERITE, HEAD);
    public static final Item ETHERITE_CHESTPLATE = baseArmorItem(ETHERITE, CHEST);
    public static final Item ETHERITE_LEGGINGS = baseArmorItem(ETHERITE, LEGS);
    public static final Item ETHERITE_BOOTS = baseArmorItem(ETHERITE, FEET);
    public static final Item HALLOWED_HELMET = baseArmorItem(HALLOWED, HEAD);
    public static final Item HALLOWED_CHESTPLATE = baseArmorItem(HALLOWED, CHEST);
    public static final Item HALLOWED_LEGGINGS = baseArmorItem(HALLOWED, LEGS);
    public static final Item HALLOWED_BOOTS = baseArmorItem(HALLOWED, FEET);
    public static final Item KYBER_HELMET = baseArmorItem(KYBER, HEAD);
    public static final Item KYBER_CHESTPLATE = baseArmorItem(KYBER, CHEST);
    public static final Item KYBER_LEGGINGS = baseArmorItem(KYBER, LEGS);
    public static final Item KYBER_BOOTS = baseArmorItem(KYBER, FEET);

    public static final Item MIDAS_GOLD_HELMET = baseArmorItem(MIDAS_GOLD, HEAD);
    public static final Item MIDAS_GOLD_CHESTPLATE = baseArmorItem(MIDAS_GOLD, CHEST);
    public static final Item MIDAS_GOLD_LEGGINGS = baseArmorItem(MIDAS_GOLD, LEGS);
    public static final Item MIDAS_GOLD_BOOTS = baseArmorItem(MIDAS_GOLD, FEET);
    public static final Item MYTHRIL_HELMET = baseArmorItem(MYTHRIL, HEAD);
    public static final Item MYTHRIL_CHESTPLATE = baseArmorItem(MYTHRIL, CHEST);
    public static final Item MYTHRIL_LEGGINGS = baseArmorItem(MYTHRIL, LEGS);
    public static final Item MYTHRIL_BOOTS = baseArmorItem(MYTHRIL, FEET);
    public static final Item ORICHALCUM_HELMET = baseArmorItem(ORICHALCUM, HEAD);
    public static final Item ORICHALCUM_CHESTPLATE = baseArmorItem(ORICHALCUM, CHEST);
    public static final Item ORICHALCUM_LEGGINGS = baseArmorItem(ORICHALCUM, LEGS);
    public static final Item ORICHALCUM_BOOTS = baseArmorItem(ORICHALCUM, FEET);
    public static final Item OSMIUM_HELMET = baseArmorItem(OSMIUM, HEAD);
    public static final Item OSMIUM_CHESTPLATE = baseArmorItem(OSMIUM, CHEST);
    public static final Item OSMIUM_LEGGINGS = baseArmorItem(OSMIUM, LEGS);
    public static final Item OSMIUM_BOOTS = baseArmorItem(OSMIUM, FEET);
    public static final Item PALLADIUM_HELMET = fireproofArmorItem(PALLADIUM, HEAD);
    public static final Item PALLADIUM_CHESTPLATE = fireproofArmorItem(PALLADIUM, CHEST);
    public static final Item PALLADIUM_LEGGINGS = fireproofArmorItem(PALLADIUM, LEGS);
    public static final Item PALLADIUM_BOOTS = fireproofArmorItem(PALLADIUM, FEET);
    public static final Item PROMETHEUM_HELMET = baseArmorItem(PROMETHEUM, HEAD);
    public static final Item PROMETHEUM_CHESTPLATE = baseArmorItem(PROMETHEUM, CHEST);
    public static final Item PROMETHEUM_LEGGINGS = baseArmorItem(PROMETHEUM, LEGS);
    public static final Item PROMETHEUM_BOOTS = baseArmorItem(PROMETHEUM, FEET);
    public static final Item QUICKSILVER_HELMET = baseArmorItem(QUICKSILVER, HEAD);
    public static final Item QUICKSILVER_CHESTPLATE = baseArmorItem(QUICKSILVER, CHEST);
    public static final Item QUICKSILVER_LEGGINGS = baseArmorItem(QUICKSILVER, LEGS);
    public static final Item QUICKSILVER_BOOTS = baseArmorItem(QUICKSILVER, FEET);
    public static final Item RUNITE_HELMET = baseArmorItem(RUNITE, HEAD);
    public static final Item RUNITE_CHESTPLATE = baseArmorItem(RUNITE, CHEST);
    public static final Item RUNITE_LEGGINGS = baseArmorItem(RUNITE, LEGS);
    public static final Item RUNITE_BOOTS = baseArmorItem(RUNITE, FEET);
    public static final Item SILVER_HELMET = baseArmorItem(SILVER, HEAD);
    public static final Item SILVER_CHESTPLATE = baseArmorItem(SILVER, CHEST);
    public static final Item SILVER_LEGGINGS = baseArmorItem(SILVER, LEGS);
    public static final Item SILVER_BOOTS = baseArmorItem(SILVER, FEET);
    public static final Item STAR_PLATINUM_HELMET = baseArmorItem(STAR_PLATINUM, HEAD);
    public static final Item STAR_PLATINUM_CHESTPLATE = baseArmorItem(STAR_PLATINUM, CHEST);
    public static final Item STAR_PLATINUM_LEGGINGS = baseArmorItem(STAR_PLATINUM, LEGS);
    public static final Item STAR_PLATINUM_BOOTS = baseArmorItem(STAR_PLATINUM, FEET);
    public static final Item STEEL_HELMET = baseArmorItem(STEEL, HEAD);
    public static final Item STEEL_CHESTPLATE = baseArmorItem(STEEL, CHEST);
    public static final Item STEEL_LEGGINGS = baseArmorItem(STEEL, LEGS);
    public static final Item STEEL_BOOTS = baseArmorItem(STEEL, FEET);
    public static final Item STORMYX_HELMET = baseArmorItem(STORMYX, HEAD);
    public static final Item STORMYX_CHESTPLATE = baseArmorItem(STORMYX, CHEST);
    public static final Item STORMYX_LEGGINGS = baseArmorItem(STORMYX, LEGS);
    public static final Item STORMYX_BOOTS = baseArmorItem(STORMYX, FEET);

    private static Item baseArmorItem(ArmorMaterial material, EquipmentSlot slot) {
        return new ArmorItem(material, slot, new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR));
    }

    private static Item fireproofArmorItem(ArmorMaterial material, EquipmentSlot slot) {
        return new ArmorItem(material, slot, new Item.Settings().group(MythicMetals.MYTHICMETALS_ARMOR).fireproof());
    }
    
    public static void register() {
        //Register Armor

        ADAMANTITE.register("adamantite");
        METALLURGIUM.register("metallurgium");

        RegistryHelper.item( "aetherium_helmet", AETHERIUM_HELMET);
        RegistryHelper.item( "aetherium_chestplate", AETHERIUM_CHESTPLATE);
        RegistryHelper.item( "aetherium_leggings", AETHERIUM_LEGGINGS);
        RegistryHelper.item( "aetherium_boots", AETHERIUM_BOOTS);
        RegistryHelper.item( "aquarium_helmet", AQUARIUM_HELMET);
        RegistryHelper.item( "aquarium_chestplate", AQUARIUM_CHESTPLATE);
        RegistryHelper.item( "aquarium_leggings", AQUARIUM_LEGGINGS);
        RegistryHelper.item( "aquarium_boots", AQUARIUM_BOOTS);
        RegistryHelper.item( "banglum_helmet", BANGLUM_HELMET);
        RegistryHelper.item( "banglum_chestplate", BANGLUM_CHESTPLATE);
        RegistryHelper.item( "banglum_leggings", BANGLUM_LEGGINGS);
        RegistryHelper.item( "banglum_boots", BANGLUM_BOOTS);
        RegistryHelper.item( "bronze_helmet", BRONZE_HELMET);
        RegistryHelper.item( "bronze_chestplate", BRONZE_CHESTPLATE);
        RegistryHelper.item( "bronze_leggings", BRONZE_LEGGINGS);
        RegistryHelper.item( "bronze_boots", BRONZE_BOOTS);
        RegistryHelper.item( "carmot_helmet", CARMOT_HELMET);
        RegistryHelper.item( "carmot_chestplate", CARMOT_CHESTPLATE);
        RegistryHelper.item( "carmot_leggings", CARMOT_LEGGINGS);
        RegistryHelper.item( "carmot_boots", CARMOT_BOOTS);
        RegistryHelper.item( "celestium_helmet", CELESTIUM_HELMET);
        RegistryHelper.item( "celestium_chestplate", CELESTIUM_CHESTPLATE);
        RegistryHelper.item( "celestium_leggings", CELESTIUM_LEGGINGS);
        RegistryHelper.item( "celestium_boots", CELESTIUM_BOOTS);
        RegistryHelper.item( "copper_helmet", COPPER_HELMET);
        RegistryHelper.item( "copper_chestplate", COPPER_CHESTPLATE);
        RegistryHelper.item( "copper_leggings", COPPER_LEGGINGS);
        RegistryHelper.item( "copper_boots", COPPER_BOOTS);
        RegistryHelper.item( "discordium_helmet", DISCORDIUM_HELMET);
        RegistryHelper.item( "discordium_chestplate", DISCORDIUM_CHESTPLATE);
        RegistryHelper.item( "discordium_leggings", DISCORDIUM_LEGGINGS);
        RegistryHelper.item( "discordium_boots", DISCORDIUM_BOOTS);
        RegistryHelper.item( "durasteel_helmet", DURASTEEL_HELMET);
        RegistryHelper.item( "durasteel_chestplate", DURASTEEL_CHESTPLATE);
        RegistryHelper.item( "durasteel_leggings", DURASTEEL_LEGGINGS);
        RegistryHelper.item( "durasteel_boots", DURASTEEL_BOOTS);
        RegistryHelper.item( "etherite_helmet", ETHERITE_HELMET);
        RegistryHelper.item( "etherite_chestplate", ETHERITE_CHESTPLATE);
        RegistryHelper.item( "etherite_leggings", ETHERITE_LEGGINGS);
        RegistryHelper.item( "etherite_boots", ETHERITE_BOOTS);
        RegistryHelper.item( "hallowed_helmet", HALLOWED_HELMET);
        RegistryHelper.item( "hallowed_chestplate", HALLOWED_CHESTPLATE);
        RegistryHelper.item( "hallowed_leggings", HALLOWED_LEGGINGS);
        RegistryHelper.item( "hallowed_boots", HALLOWED_BOOTS);
        RegistryHelper.item( "kyber_helmet", KYBER_HELMET);
        RegistryHelper.item( "kyber_chestplate", KYBER_CHESTPLATE);
        RegistryHelper.item( "kyber_leggings", KYBER_LEGGINGS);
        RegistryHelper.item( "kyber_boots", KYBER_BOOTS);

        RegistryHelper.item( "midas_gold_helmet", MIDAS_GOLD_HELMET);
        RegistryHelper.item( "midas_gold_chestplate", MIDAS_GOLD_CHESTPLATE);
        RegistryHelper.item( "midas_gold_leggings", MIDAS_GOLD_LEGGINGS);
        RegistryHelper.item( "midas_gold_boots", MIDAS_GOLD_BOOTS);
        RegistryHelper.item( "mythril_helmet", MYTHRIL_HELMET);
        RegistryHelper.item( "mythril_chestplate", MYTHRIL_CHESTPLATE);
        RegistryHelper.item( "mythril_leggings", MYTHRIL_LEGGINGS);
        RegistryHelper.item( "mythril_boots", MYTHRIL_BOOTS);
        RegistryHelper.item( "orichalcum_helmet", ORICHALCUM_HELMET);
        RegistryHelper.item( "orichalcum_chestplate", ORICHALCUM_CHESTPLATE);
        RegistryHelper.item( "orichalcum_leggings", ORICHALCUM_LEGGINGS);
        RegistryHelper.item( "orichalcum_boots", ORICHALCUM_BOOTS);
        RegistryHelper.item( "osmium_helmet", OSMIUM_HELMET);
        RegistryHelper.item( "osmium_chestplate", OSMIUM_CHESTPLATE);
        RegistryHelper.item( "osmium_leggings", OSMIUM_LEGGINGS);
        RegistryHelper.item( "osmium_boots", OSMIUM_BOOTS);
        RegistryHelper.item( "palladium_helmet", PALLADIUM_HELMET);
        RegistryHelper.item( "palladium_chestplate", PALLADIUM_CHESTPLATE);
        RegistryHelper.item( "palladium_leggings", PALLADIUM_LEGGINGS);
        RegistryHelper.item( "palladium_boots", PALLADIUM_BOOTS);
        RegistryHelper.item( "prometheum_helmet", PROMETHEUM_HELMET);
        RegistryHelper.item( "prometheum_chestplate", PROMETHEUM_CHESTPLATE);
        RegistryHelper.item( "prometheum_leggings", PROMETHEUM_LEGGINGS);
        RegistryHelper.item( "prometheum_boots", PROMETHEUM_BOOTS);
        RegistryHelper.item( "quicksilver_helmet", QUICKSILVER_HELMET);
        RegistryHelper.item( "quicksilver_chestplate", QUICKSILVER_CHESTPLATE);
        RegistryHelper.item( "quicksilver_leggings", QUICKSILVER_LEGGINGS);
        RegistryHelper.item( "quicksilver_boots", QUICKSILVER_BOOTS);
        RegistryHelper.item( "runite_helmet", RUNITE_HELMET);
        RegistryHelper.item( "runite_chestplate", RUNITE_CHESTPLATE);
        RegistryHelper.item( "runite_leggings", RUNITE_LEGGINGS);
        RegistryHelper.item( "runite_boots", RUNITE_BOOTS);
        RegistryHelper.item( "silver_helmet", SILVER_HELMET);
        RegistryHelper.item( "silver_chestplate", SILVER_CHESTPLATE);
        RegistryHelper.item( "silver_leggings", SILVER_LEGGINGS);
        RegistryHelper.item( "silver_boots", SILVER_BOOTS);
        RegistryHelper.item( "star_platinum_helmet", STAR_PLATINUM_HELMET);
        RegistryHelper.item( "star_platinum_chestplate", STAR_PLATINUM_CHESTPLATE);
        RegistryHelper.item( "star_platinum_leggings", STAR_PLATINUM_LEGGINGS);
        RegistryHelper.item( "star_platinum_boots", STAR_PLATINUM_BOOTS);
        RegistryHelper.item( "steel_helmet", STEEL_HELMET);
        RegistryHelper.item( "steel_chestplate", STEEL_CHESTPLATE);
        RegistryHelper.item( "steel_leggings", STEEL_LEGGINGS);
        RegistryHelper.item( "steel_boots", STEEL_BOOTS);
        RegistryHelper.item( "stormyx_helmet", STORMYX_HELMET);
        RegistryHelper.item( "stormyx_chestplate", STORMYX_CHESTPLATE);
        RegistryHelper.item( "stormyx_leggings", STORMYX_LEGGINGS);
        RegistryHelper.item( "stormyx_boots", STORMYX_BOOTS);
    }

}
