package nourl.mythicmetals.registry;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.SwordItem;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;
import nourl.mythicmetals.tools.AxeBase;
import nourl.mythicmetals.tools.HoeBase;
import nourl.mythicmetals.tools.PickaxeBase;
import nourl.mythicmetals.tools.ToolMaterials;

public class RegisterTools {
    //SWORDS
    public static final Item ADAMANTITE_SWORD = new SwordItem(ToolMaterials.ADAMANTITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_SWORD = new SwordItem(ToolMaterials.AETHERIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_SWORD = new SwordItem(ToolMaterials.AQUARIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_SWORD = new SwordItem(ToolMaterials.BANGLUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_SWORD = new SwordItem(ToolMaterials.BRONZE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_SWORD = new SwordItem(ToolMaterials.CARMOT, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_SWORD = new SwordItem(ToolMaterials.CELESTIUM, 3, -2.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_SWORD = new SwordItem(ToolMaterials.COPPER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_SWORD = new SwordItem(ToolMaterials.DISCORDIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_SWORD = new SwordItem(ToolMaterials.DURASTEEL, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ETHERITE_SWORD = new SwordItem(ToolMaterials.ETHERITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_SWORD = new SwordItem(ToolMaterials.HALLOWED, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_SWORD = new SwordItem(ToolMaterials.KYBER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_SWORD = new SwordItem(ToolMaterials.METALLURGIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_SWORD = new SwordItem(ToolMaterials.MYTHRIL, 3, -2.2F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_SWORD = new SwordItem(ToolMaterials.ORICHALCUM, 3, -2.5F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_SWORD = new SwordItem(ToolMaterials.OSMIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_SWORD = new SwordItem(ToolMaterials.PALLADIUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_SWORD = new SwordItem(ToolMaterials.PROMETHEUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_SWORD = new SwordItem(ToolMaterials.QUADRILLUM, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_SWORD = new SwordItem(ToolMaterials.QUICKSILVER, 3, -2.2F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_SWORD = new SwordItem(ToolMaterials.RUNITE, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_SWORD = new SwordItem(ToolMaterials.SILVER, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_SWORD = new SwordItem(ToolMaterials.STAR_PLATINUM, 3, -2.3F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_SWORD = new SwordItem(ToolMaterials.STEEL, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_SWORD = new SwordItem(ToolMaterials.STORMYX, 3, -2.4F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));

    public static final Item RED_AEGIS_SWORD = new SwordItem(ToolMaterials.CELESTIUM, 5, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item WHITE_AEGIS_SWORD = new SwordItem(ToolMaterials.CELESTIUM, 3, -2.5F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));

    //PICKAXES
    public static final Item ADAMANTITE_PICKAXE = new PickaxeBase(ToolMaterials.ADAMANTITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_PICKAXE = new PickaxeBase(ToolMaterials.AETHERIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_PICKAXE = new PickaxeBase(ToolMaterials.AQUARIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_PICKAXE = new PickaxeBase(ToolMaterials.BANGLUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_PICKAXE = new PickaxeBase(ToolMaterials.BRONZE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_PICKAXE = new PickaxeBase(ToolMaterials.CARMOT, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_PICKAXE = new PickaxeBase(ToolMaterials.CELESTIUM, 2, -2.6F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_PICKAXE = new PickaxeBase(ToolMaterials.COPPER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_PICKAXE = new PickaxeBase(ToolMaterials.DISCORDIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_PICKAXE = new PickaxeBase(ToolMaterials.DURASTEEL, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_PICKAXE = new PickaxeBase(ToolMaterials.HALLOWED, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_PICKAXE = new PickaxeBase(ToolMaterials.KYBER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_PICKAXE = new PickaxeBase(ToolMaterials.METALLURGIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_PICKAXE = new PickaxeBase(ToolMaterials.MYTHRIL, 2, -2.6F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_PICKAXE = new PickaxeBase(ToolMaterials.ORICHALCUM, 2, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_PICKAXE = new PickaxeBase(ToolMaterials.OSMIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_PICKAXE = new PickaxeBase(ToolMaterials.PALLADIUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_PICKAXE = new PickaxeBase(ToolMaterials.PROMETHEUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_PICKAXE = new PickaxeBase(ToolMaterials.QUADRILLUM, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_PICKAXE = new PickaxeBase(ToolMaterials.QUICKSILVER, 2, -2.6F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_PICKAXE = new PickaxeBase(ToolMaterials.RUNITE, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_PICKAXE = new PickaxeBase(ToolMaterials.SILVER, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_PICKAXE = new PickaxeBase(ToolMaterials.STAR_PLATINUM, 2, -2.7F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_PICKAXE = new PickaxeBase(ToolMaterials.STEEL, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_PICKAXE = new PickaxeBase(ToolMaterials.STORMYX, 2, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    //AXES
    public static final Item ADAMANTITE_AXE = new AxeBase(ToolMaterials.ADAMANTITE, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_AXE = new AxeBase(ToolMaterials.AETHERIUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_AXE = new AxeBase(ToolMaterials.AQUARIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_AXE = new AxeBase(ToolMaterials.BANGLUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_AXE = new AxeBase(ToolMaterials.BRONZE, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_AXE = new AxeBase(ToolMaterials.CARMOT, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_AXE = new AxeBase(ToolMaterials.CELESTIUM, 4, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_AXE = new AxeBase(ToolMaterials.COPPER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_AXE = new AxeBase(ToolMaterials.DISCORDIUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_AXE = new AxeBase(ToolMaterials.DURASTEEL, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_AXE = new AxeBase(ToolMaterials.HALLOWED, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_AXE = new AxeBase(ToolMaterials.KYBER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_AXE = new AxeBase(ToolMaterials.METALLURGIUM, 5, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_AXE = new AxeBase(ToolMaterials.MYTHRIL, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_AXE = new AxeBase(ToolMaterials.ORICHALCUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_AXE = new AxeBase(ToolMaterials.OSMIUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_AXE = new AxeBase(ToolMaterials.PALLADIUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_AXE = new AxeBase(ToolMaterials.PROMETHEUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_AXE = new AxeBase(ToolMaterials.QUADRILLUM, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_AXE = new AxeBase(ToolMaterials.QUICKSILVER, 4, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_AXE = new AxeBase(ToolMaterials.RUNITE, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_AXE = new AxeBase(ToolMaterials.SILVER, 4, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_AXE = new AxeBase(ToolMaterials.STAR_PLATINUM, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_AXE = new AxeBase(ToolMaterials.STEEL, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_AXE = new AxeBase(ToolMaterials.STORMYX, 4, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    //SHOVELS
    public static final Item ADAMANTITE_SHOVEL = new ShovelItem(ToolMaterials.ADAMANTITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_SHOVEL = new ShovelItem(ToolMaterials.AETHERIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_SHOVEL = new ShovelItem(ToolMaterials.AQUARIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_SHOVEL = new ShovelItem(ToolMaterials.BANGLUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_SHOVEL = new ShovelItem(ToolMaterials.BRONZE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_SHOVEL = new ShovelItem(ToolMaterials.CARMOT, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_SHOVEL = new ShovelItem(ToolMaterials.CELESTIUM, 1, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_SHOVEL = new ShovelItem(ToolMaterials.COPPER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_SHOVEL = new ShovelItem(ToolMaterials.DISCORDIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_SHOVEL = new ShovelItem(ToolMaterials.DURASTEEL, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_SHOVEL = new ShovelItem(ToolMaterials.HALLOWED, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_SHOVEL = new ShovelItem(ToolMaterials.KYBER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_SHOVEL = new ShovelItem(ToolMaterials.METALLURGIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_SHOVEL = new ShovelItem(ToolMaterials.MYTHRIL, 1, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_SHOVEL = new ShovelItem(ToolMaterials.ORICHALCUM, 1, -3.1F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_SHOVEL = new ShovelItem(ToolMaterials.OSMIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_SHOVEL = new ShovelItem(ToolMaterials.PALLADIUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_SHOVEL = new ShovelItem(ToolMaterials.PROMETHEUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_SHOVEL = new ShovelItem(ToolMaterials.QUADRILLUM, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_SHOVEL = new ShovelItem(ToolMaterials.QUICKSILVER, 1, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_SHOVEL = new ShovelItem(ToolMaterials.RUNITE, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_SHOVEL = new ShovelItem(ToolMaterials.SILVER, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_SHOVEL = new ShovelItem(ToolMaterials.STAR_PLATINUM, 1, -2.8F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_SHOVEL = new ShovelItem(ToolMaterials.STEEL, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_SHOVEL = new ShovelItem(ToolMaterials.STORMYX, 1, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    //HOES
    public static final Item ADAMANTITE_HOE = new HoeBase(ToolMaterials.ADAMANTITE, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AETHERIUM_HOE = new HoeBase(ToolMaterials.AETHERIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item AQUARIUM_HOE = new HoeBase(ToolMaterials.AQUARIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BANGLUM_HOE = new HoeBase(ToolMaterials.BANGLUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item BRONZE_HOE = new HoeBase(ToolMaterials.BRONZE, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CARMOT_HOE = new HoeBase(ToolMaterials.CARMOT, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item CELESTIUM_HOE = new HoeBase(ToolMaterials.CELESTIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item COPPER_HOE = new HoeBase(ToolMaterials.COPPER, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DISCORDIUM_HOE = new HoeBase(ToolMaterials.DISCORDIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item DURASTEEL_HOE = new HoeBase(ToolMaterials.DURASTEEL, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item HALLOWED_HOE = new HoeBase(ToolMaterials.HALLOWED, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item KYBER_HOE = new HoeBase(ToolMaterials.KYBER, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item METALLURGIUM_HOE = new HoeBase(ToolMaterials.METALLURGIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item MYTHRIL_HOE = new HoeBase(ToolMaterials.MYTHRIL, 0, -2.5F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item ORICHALCUM_HOE = new HoeBase(ToolMaterials.ORICHALCUM, 0, -3.0F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item OSMIUM_HOE = new HoeBase(ToolMaterials.OSMIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item PALLADIUM_HOE = new HoeBase(ToolMaterials.PALLADIUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS).fireproof());
    public static final Item PROMETHEUM_HOE = new HoeBase(ToolMaterials.PROMETHEUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUADRILLUM_HOE = new HoeBase(ToolMaterials.QUADRILLUM, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item QUICKSILVER_HOE = new HoeBase(ToolMaterials.QUICKSILVER, 0, -2.7F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item RUNITE_HOE = new HoeBase(ToolMaterials.RUNITE, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item SILVER_HOE = new HoeBase(ToolMaterials.SILVER, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STAR_PLATINUM_HOE = new HoeBase(ToolMaterials.STAR_PLATINUM, 0, -2.7F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STEEL_HOE = new HoeBase(ToolMaterials.STEEL, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));
    public static final Item STORMYX_HOE = new HoeBase(ToolMaterials.STORMYX, 0, -2.9F, new Item.Settings().group(MythicMetals.MYTHICMETALS_TOOLS));

    public static class Frogery {
        public static final Item FROGE = new Item(new FabricItemSettings().rarity(Rarity.EPIC).fireproof().equipmentSlot(stack -> EquipmentSlot.HEAD));
    }

    public static void register() {
        RegistryHelper.item("adamantite_axe", ADAMANTITE_AXE);
        RegistryHelper.item("adamantite_hoe", ADAMANTITE_HOE);
        RegistryHelper.item("adamantite_pickaxe", ADAMANTITE_PICKAXE);
        RegistryHelper.item("adamantite_shovel", ADAMANTITE_SHOVEL);
        RegistryHelper.item("adamantite_sword", ADAMANTITE_SWORD);
        RegistryHelper.item("aetherium_axe", AETHERIUM_AXE);
        RegistryHelper.item("aetherium_hoe", AETHERIUM_HOE);
        RegistryHelper.item("aetherium_pickaxe", AETHERIUM_PICKAXE);
        RegistryHelper.item("aetherium_shovel", AETHERIUM_SHOVEL);
        RegistryHelper.item("aetherium_sword", AETHERIUM_SWORD);
        RegistryHelper.item("aquarium_axe", AQUARIUM_AXE);
        RegistryHelper.item("aquarium_hoe", AQUARIUM_HOE);
        RegistryHelper.item("aquarium_pickaxe", AQUARIUM_PICKAXE);
        RegistryHelper.item("aquarium_shovel", AQUARIUM_SHOVEL);
        RegistryHelper.item("aquarium_sword", AQUARIUM_SWORD);
        RegistryHelper.item("banglum_axe", BANGLUM_AXE);
        RegistryHelper.item("banglum_hoe", BANGLUM_HOE);
        RegistryHelper.item("banglum_pickaxe", BANGLUM_PICKAXE);
        RegistryHelper.item("banglum_shovel", BANGLUM_SHOVEL);
        RegistryHelper.item("banglum_sword", BANGLUM_SWORD);
        RegistryHelper.item("bronze_axe", BRONZE_AXE);
        RegistryHelper.item("bronze_hoe", BRONZE_HOE);
        RegistryHelper.item("bronze_pickaxe", BRONZE_PICKAXE);
        RegistryHelper.item("bronze_shovel", BRONZE_SHOVEL);
        RegistryHelper.item("bronze_sword", BRONZE_SWORD);
        RegistryHelper.item("carmot_axe", CARMOT_AXE);
        RegistryHelper.item("carmot_hoe", CARMOT_HOE);
        RegistryHelper.item("carmot_pickaxe", CARMOT_PICKAXE);
        RegistryHelper.item("carmot_shovel", CARMOT_SHOVEL);
        RegistryHelper.item("carmot_sword", CARMOT_SWORD);
        RegistryHelper.item("celestium_axe", CELESTIUM_AXE);
        RegistryHelper.item("celestium_hoe", CELESTIUM_HOE);
        RegistryHelper.item("celestium_pickaxe", CELESTIUM_PICKAXE);
        RegistryHelper.item("celestium_shovel", CELESTIUM_SHOVEL);
        RegistryHelper.item("celestium_sword", CELESTIUM_SWORD);
        RegistryHelper.item("copper_axe", COPPER_AXE);
        RegistryHelper.item("copper_hoe", COPPER_HOE);
        RegistryHelper.item("copper_pickaxe", COPPER_PICKAXE);
        RegistryHelper.item("copper_shovel", COPPER_SHOVEL);
        RegistryHelper.item("copper_sword", COPPER_SWORD);
        RegistryHelper.item("discordium_axe", DISCORDIUM_AXE);
        RegistryHelper.item("discordium_hoe", DISCORDIUM_HOE);
        RegistryHelper.item("discordium_pickaxe", DISCORDIUM_PICKAXE);
        RegistryHelper.item("discordium_shovel", DISCORDIUM_SHOVEL);
        RegistryHelper.item("discordium_sword", DISCORDIUM_SWORD);
        RegistryHelper.item("durasteel_axe", DURASTEEL_AXE);
        RegistryHelper.item("durasteel_hoe", DURASTEEL_HOE);
        RegistryHelper.item("durasteel_pickaxe", DURASTEEL_PICKAXE);
        RegistryHelper.item("durasteel_shovel", DURASTEEL_SHOVEL);
        RegistryHelper.item("durasteel_sword", DURASTEEL_SWORD);
        RegistryHelper.item("etherite_sword", ETHERITE_SWORD);
        RegistryHelper.item("kyber_axe", KYBER_AXE);
        RegistryHelper.item("kyber_hoe", KYBER_HOE);
        RegistryHelper.item("kyber_pickaxe", KYBER_PICKAXE);
        RegistryHelper.item("kyber_shovel", KYBER_SHOVEL);
        RegistryHelper.item("kyber_sword", KYBER_SWORD);
        RegistryHelper.item("hallowed_axe", HALLOWED_AXE);
        RegistryHelper.item("hallowed_hoe", HALLOWED_HOE);
        RegistryHelper.item("hallowed_pickaxe", HALLOWED_PICKAXE);
        RegistryHelper.item("hallowed_shovel", HALLOWED_SHOVEL);
        RegistryHelper.item("hallowed_sword", HALLOWED_SWORD);
        RegistryHelper.item("metallurgium_axe", METALLURGIUM_AXE);
        RegistryHelper.item("metallurgium_hoe", METALLURGIUM_HOE);
        RegistryHelper.item("metallurgium_pickaxe", METALLURGIUM_PICKAXE);
        RegistryHelper.item("metallurgium_shovel", METALLURGIUM_SHOVEL);
        RegistryHelper.item("metallurgium_sword", METALLURGIUM_SWORD);
        RegistryHelper.item("mythril_axe", MYTHRIL_AXE);
        RegistryHelper.item("mythril_hoe", MYTHRIL_HOE);
        RegistryHelper.item("mythril_pickaxe", MYTHRIL_PICKAXE);
        RegistryHelper.item("mythril_shovel", MYTHRIL_SHOVEL);
        RegistryHelper.item("mythril_sword", MYTHRIL_SWORD);
        RegistryHelper.item("orichalcum_axe", ORICHALCUM_AXE);
        RegistryHelper.item("orichalcum_hoe", ORICHALCUM_HOE);
        RegistryHelper.item("orichalcum_pickaxe", ORICHALCUM_PICKAXE);
        RegistryHelper.item("orichalcum_shovel", ORICHALCUM_SHOVEL);
        RegistryHelper.item("orichalcum_sword", ORICHALCUM_SWORD);
        RegistryHelper.item("osmium_axe", OSMIUM_AXE);
        RegistryHelper.item("osmium_hoe", OSMIUM_HOE);
        RegistryHelper.item("froge_ingot", Frogery.FROGE);
        RegistryHelper.item("osmium_pickaxe", OSMIUM_PICKAXE);
        RegistryHelper.item("osmium_shovel", OSMIUM_SHOVEL);
        RegistryHelper.item("osmium_sword", OSMIUM_SWORD);
        RegistryHelper.item("palladium_axe", PALLADIUM_AXE);
        RegistryHelper.item("palladium_hoe", PALLADIUM_HOE);
        RegistryHelper.item("palladium_pickaxe", PALLADIUM_PICKAXE);
        RegistryHelper.item("palladium_shovel", PALLADIUM_SHOVEL);
        RegistryHelper.item("palladium_sword", PALLADIUM_SWORD);
        RegistryHelper.item("prometheum_axe", PROMETHEUM_AXE);
        RegistryHelper.item("prometheum_hoe", PROMETHEUM_HOE);
        RegistryHelper.item("prometheum_pickaxe", PROMETHEUM_PICKAXE);
        RegistryHelper.item("prometheum_shovel", PROMETHEUM_SHOVEL);
        RegistryHelper.item("prometheum_sword", PROMETHEUM_SWORD);
        RegistryHelper.item("quadrillum_axe", QUADRILLUM_AXE);
        RegistryHelper.item("quadrillum_hoe", QUADRILLUM_HOE);
        RegistryHelper.item("quadrillum_pickaxe", QUADRILLUM_PICKAXE);
        RegistryHelper.item("quadrillum_shovel", QUADRILLUM_SHOVEL);
        RegistryHelper.item("quadrillum_sword", QUADRILLUM_SWORD);
        RegistryHelper.item("quicksilver_axe", QUICKSILVER_AXE);
        RegistryHelper.item("quicksilver_hoe", QUICKSILVER_HOE);
        RegistryHelper.item("quicksilver_pickaxe", QUICKSILVER_PICKAXE);
        RegistryHelper.item("quicksilver_shovel", QUICKSILVER_SHOVEL);
        RegistryHelper.item("quicksilver_sword", QUICKSILVER_SWORD);
        RegistryHelper.item("runite_axe", RUNITE_AXE);
        RegistryHelper.item("runite_hoe", RUNITE_HOE);
        RegistryHelper.item("runite_pickaxe", RUNITE_PICKAXE);
        RegistryHelper.item("runite_shovel", RUNITE_SHOVEL);
        RegistryHelper.item("runite_sword", RUNITE_SWORD);
        RegistryHelper.item("silver_axe", SILVER_AXE);
        RegistryHelper.item("silver_hoe", SILVER_HOE);
        RegistryHelper.item("silver_pickaxe", SILVER_PICKAXE);
        RegistryHelper.item("silver_shovel", SILVER_SHOVEL);
        RegistryHelper.item("silver_sword", SILVER_SWORD);
        RegistryHelper.item("star_platinum_axe", STAR_PLATINUM_AXE);
        RegistryHelper.item("star_platinum_hoe", STAR_PLATINUM_HOE);
        RegistryHelper.item("star_platinum_pickaxe", STAR_PLATINUM_PICKAXE);
        RegistryHelper.item("star_platinum_shovel", STAR_PLATINUM_SHOVEL);
        RegistryHelper.item("star_platinum_sword", STAR_PLATINUM_SWORD);
        RegistryHelper.item("steel_axe", STEEL_AXE);
        RegistryHelper.item("steel_hoe", STEEL_HOE);
        RegistryHelper.item("steel_pickaxe", STEEL_PICKAXE);
        RegistryHelper.item("steel_shovel", STEEL_SHOVEL);
        RegistryHelper.item("steel_sword", STEEL_SWORD);
        RegistryHelper.item("stormyx_axe", STORMYX_AXE);
        RegistryHelper.item("stormyx_hoe", STORMYX_HOE);
        RegistryHelper.item("stormyx_pickaxe", STORMYX_PICKAXE);
        RegistryHelper.item("stormyx_shovel", STORMYX_SHOVEL);
        RegistryHelper.item("stormyx_sword", STORMYX_SWORD);
        Registry.register(Registry.ITEM, new Identifier("mythicaddons","white_aegis_sword"), WHITE_AEGIS_SWORD);
        Registry.register(Registry.ITEM, new Identifier("mythicaddons","red_aegis_sword"), RED_AEGIS_SWORD);

    }
}