package nourl.mythicmetals.registry;

import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;
import nourl.mythicmetals.blocks.MythicBlocks;

public class RegisterBlocks {

    public static void register() {
        // Ores
        RegisterItem("adamantite_ore", MythicBlocks.ADAMANTITE_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("aetherium_ore", MythicBlocks.AETHERIUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("aquarium_ore", MythicBlocks.AQUARIUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("banglum_ore", MythicBlocks.BANGLUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("blackstone_stormyx_ore", MythicBlocks.BLACKSTONE_STORMYX_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("calcite_kyber_ore", MythicBlocks.CALCITE_KYBER_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("calcite_starrite_ore", MythicBlocks.CALCITE_STARRITE_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("carmot_ore", MythicBlocks.CARMOT_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("deepslate_adamantite_ore", MythicBlocks.DEEPSLATE_ADAMANTITE_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("deepslate_mythril_ore", MythicBlocks.DEEPSLATE_MYTHRIL_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("deepslate_orichalcum_ore", MythicBlocks.DEEPSLATE_ORICHALCUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("deepslate_prometheum_ore", MythicBlocks.DEEPSLATE_PROMETHEUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("kyber_ore", MythicBlocks.KYBER_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("manganese_ore", MythicBlocks.MANGANESE_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("midas_gold_ore", MythicBlocks.MIDAS_GOLD_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("mythril_ore", MythicBlocks.MYTHRIL_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("orichalcum_ore", MythicBlocks.ORICHALCUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("osmium_ore", MythicBlocks.OSMIUM_ORE, MythicMetals.MYTHICMETALS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_ore"), new BlockItem(MythicBlocks.PALLADIUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "deepslate_unobtainium_ore"), new BlockItem(MythicBlocks.DEEPSLATE_UNOBTAINIUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
        RegisterItem("platinum_ore", MythicBlocks.PLATINUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("prometheum_ore", MythicBlocks.PROMETHEUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("quadrillum_ore", MythicBlocks.QUADRILLUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("runite_ore", MythicBlocks.RUNITE_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("silver_ore", MythicBlocks.SILVER_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("smooth_basalt_orichalcum_ore", MythicBlocks.SMOOTH_BASALT_ORICHALCUM_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("starrite_ore", MythicBlocks.STARRITE_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("stormyx_ore", MythicBlocks.STORMYX_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("tin_ore", MythicBlocks.TIN_ORE, MythicMetals.MYTHICMETALS);
        RegisterItem("tuff_orichalcum_ore", MythicBlocks.TUFF_ORICHALCUM_ORE, MythicMetals.MYTHICMETALS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "unobtainium_ore"), new BlockItem(MythicBlocks.UNOBTAINIUM_ORE, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
        RegisterItem("vermiculite_ore", MythicBlocks.VERMICULITE_ORE, MythicMetals.MYTHICMETALS);

        RegisterBlock("adamantite_ore", MythicBlocks.ADAMANTITE_ORE);
        RegisterBlock("aetherium_ore", MythicBlocks.AETHERIUM_ORE);
        RegisterBlock("aquarium_ore", MythicBlocks.AQUARIUM_ORE);
        RegisterBlock("banglum_ore", MythicBlocks.BANGLUM_ORE);
        RegisterBlock("blackstone_stormyx_ore", MythicBlocks.BLACKSTONE_STORMYX_ORE);
        RegisterBlock("calcite_kyber_ore", MythicBlocks.CALCITE_KYBER_ORE);
        RegisterBlock("calcite_starrite_ore", MythicBlocks.CALCITE_STARRITE_ORE);
        RegisterBlock("carmot_ore", MythicBlocks.CARMOT_ORE);
        RegisterBlock("deepslate_adamantite_ore", MythicBlocks.DEEPSLATE_ADAMANTITE_ORE);
        RegisterBlock("deepslate_mythril_ore", MythicBlocks.DEEPSLATE_MYTHRIL_ORE);
        RegisterBlock("deepslate_orichalcum_ore", MythicBlocks.DEEPSLATE_ORICHALCUM_ORE);
        RegisterBlock("deepslate_prometheum_ore", MythicBlocks.DEEPSLATE_PROMETHEUM_ORE);
        RegisterBlock("deepslate_unobtainium_ore", MythicBlocks.DEEPSLATE_UNOBTAINIUM_ORE);
        RegisterBlock("kyber_ore", MythicBlocks.KYBER_ORE);
        RegisterBlock("manganese_ore", MythicBlocks.MANGANESE_ORE);
        RegisterBlock("midas_gold_ore", MythicBlocks.MIDAS_GOLD_ORE);
        RegisterBlock("mythril_ore", MythicBlocks.MYTHRIL_ORE);
        RegisterBlock("orichalcum_ore", MythicBlocks.ORICHALCUM_ORE);
        RegisterBlock("osmium_ore", MythicBlocks.OSMIUM_ORE);
        RegisterBlock("palladium_ore", MythicBlocks.PALLADIUM_ORE);
        RegisterBlock("platinum_ore", MythicBlocks.PLATINUM_ORE);
        RegisterBlock("prometheum_ore", MythicBlocks.PROMETHEUM_ORE);
        RegisterBlock("quadrillum_ore", MythicBlocks.QUADRILLUM_ORE);
        RegisterBlock("runite_ore", MythicBlocks.RUNITE_ORE);
        RegisterBlock("silver_ore", MythicBlocks.SILVER_ORE);
        RegisterBlock("smooth_basalt_orichalcum_ore", MythicBlocks.SMOOTH_BASALT_ORICHALCUM_ORE);
        RegisterBlock("starrite_ore", MythicBlocks.STARRITE_ORE);
        RegisterBlock("stormyx_ore", MythicBlocks.STORMYX_ORE);
        RegisterBlock("tin_ore", MythicBlocks.TIN_ORE);
        RegisterBlock("tuff_orichalcum_ore", MythicBlocks.TUFF_ORICHALCUM_ORE);
        RegisterBlock("unobtainium_ore", MythicBlocks.UNOBTAINIUM_ORE);
        RegisterBlock("vermiculite_ore", MythicBlocks.VERMICULITE_ORE);

        // Storage Blocks
        RegisterItem("adamantite_block", MythicBlocks.ADAMANTITE_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("aetherium_block", MythicBlocks.AETHERIUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("aquarium_block", MythicBlocks.AQUARIUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("banglum_block", MythicBlocks.BANGLUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("bronze_block", MythicBlocks.BRONZE_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("carmot_block", MythicBlocks.CARMOT_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("celestium_block", MythicBlocks.CELESTIUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("discordium_block", MythicBlocks.DISCORDIUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("durasteel_block", MythicBlocks.DURASTEEL_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("etherite_block", MythicBlocks.ETHERITE_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("hallowed_block", MythicBlocks.HALLOWED_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("kyber_block", MythicBlocks.KYBER_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("manganese_block", MythicBlocks.MANGANESE_BLOCK, MythicMetals.MYTHICMETALS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_block"), new BlockItem(MythicBlocks.METALLURGIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
        RegisterItem("midas_gold_block", MythicBlocks.MIDAS_GOLD_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("mythril_block", MythicBlocks.MYTHRIL_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("orichalcum_block", MythicBlocks.ORICHALCUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("osmium_block", MythicBlocks.OSMIUM_BLOCK, MythicMetals.MYTHICMETALS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_block"), new BlockItem(MythicBlocks.PALLADIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
        RegisterItem("platinum_block", MythicBlocks.PLATINUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("prometheum_block", MythicBlocks.PROMETHEUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("quadrillum_block", MythicBlocks.QUADRILLUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("quicksilver_block", MythicBlocks.QUICKSILVER_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("runite_block", MythicBlocks.RUNITE_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("silver_block", MythicBlocks.SILVER_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("starrite_block", MythicBlocks.STARRITE_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("star_platinum_block", MythicBlocks.STAR_PLATINUM_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("steel_block", MythicBlocks.STEEL_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("stormyx_block", MythicBlocks.STORMYX_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterItem("tin_block", MythicBlocks.TIN_BLOCK, MythicMetals.MYTHICMETALS);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "unobtainium_block"), new BlockItem(MythicBlocks.UNOBTAINIUM_BLOCK, new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof()));
        RegisterItem("vermiculite_block", MythicBlocks.VERMICULITE_BLOCK, MythicMetals.MYTHICMETALS);
        RegisterBlock("adamantite_block", MythicBlocks.ADAMANTITE_BLOCK);
        RegisterBlock("aetherium_block", MythicBlocks.AETHERIUM_BLOCK);
        RegisterBlock("aquarium_block", MythicBlocks.AQUARIUM_BLOCK);
        RegisterBlock("banglum_block", MythicBlocks.BANGLUM_BLOCK);
        RegisterBlock("bronze_block", MythicBlocks.BRONZE_BLOCK);
        RegisterBlock("carmot_block", MythicBlocks.CARMOT_BLOCK);
        RegisterBlock("celestium_block", MythicBlocks.CELESTIUM_BLOCK);
        RegisterBlock("discordium_block", MythicBlocks.DISCORDIUM_BLOCK);
        RegisterBlock("durasteel_block", MythicBlocks.DURASTEEL_BLOCK);
        RegisterBlock("etherite_block", MythicBlocks.ETHERITE_BLOCK);
        RegisterBlock("hallowed_block", MythicBlocks.HALLOWED_BLOCK);
        RegisterBlock("kyber_block", MythicBlocks.KYBER_BLOCK);
        RegisterBlock("manganese_block", MythicBlocks.MANGANESE_BLOCK);
        RegisterBlock("metallurgium_block", MythicBlocks.METALLURGIUM_BLOCK);
        RegisterBlock("midas_gold_block", MythicBlocks.MIDAS_GOLD_BLOCK);
        RegisterBlock("mythril_block", MythicBlocks.MYTHRIL_BLOCK);
        RegisterBlock("orichalcum_block", MythicBlocks.ORICHALCUM_BLOCK);
        RegisterBlock("osmium_block", MythicBlocks.OSMIUM_BLOCK);
        RegisterBlock("palladium_block", MythicBlocks.PALLADIUM_BLOCK);
        RegisterBlock("platinum_block", MythicBlocks.PLATINUM_BLOCK);
        RegisterBlock("prometheum_block", MythicBlocks.PROMETHEUM_BLOCK);
        RegisterBlock("quadrillum_block", MythicBlocks.QUADRILLUM_BLOCK);
        RegisterBlock("quicksilver_block", MythicBlocks.QUICKSILVER_BLOCK);
        RegisterBlock("runite_block", MythicBlocks.RUNITE_BLOCK);
        RegisterBlock("silver_block", MythicBlocks.SILVER_BLOCK);
        RegisterBlock("starrite_block", MythicBlocks.STARRITE_BLOCK);
        RegisterBlock("star_platinum_block", MythicBlocks.STAR_PLATINUM_BLOCK);
        RegisterBlock("steel_block", MythicBlocks.STEEL_BLOCK);
        RegisterBlock("stormyx_block", MythicBlocks.STORMYX_BLOCK);
        RegisterBlock("tin_block", MythicBlocks.TIN_BLOCK);
        RegisterBlock("unobtainium_block", MythicBlocks.UNOBTAINIUM_BLOCK);
        RegisterBlock("vermiculite_block", MythicBlocks.VERMICULITE_BLOCK);

        // Anvils
        RegisterItem("adamantite_anvil", MythicBlocks.ADAMANTITE_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("aetherium_anvil", MythicBlocks.AETHERIUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("aquarium_anvil", MythicBlocks.AQUARIUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("banglum_anvil", MythicBlocks.BANGLUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("bronze_anvil", MythicBlocks.BRONZE_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("carmot_anvil", MythicBlocks.CARMOT_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("celestium_anvil", MythicBlocks.CELESTIUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("discordium_anvil", MythicBlocks.DISCORDIUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("durasteel_anvil", MythicBlocks.DURASTEEL_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("etherite_anvil", MythicBlocks.ETHERITE_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("hallowed_anvil", MythicBlocks.HALLOWED_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("kyber_anvil", MythicBlocks.KYBER_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("manganese_anvil", MythicBlocks.MANGANESE_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_anvil"), new BlockItem(MythicBlocks.METALLURGIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR).fireproof()));
        RegisterItem("midas_gold_anvil", MythicBlocks.MIDAS_GOLD_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("mythril_anvil", MythicBlocks.MYTHRIL_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("orichalcum_anvil", MythicBlocks.ORICHALCUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("osmium_anvil", MythicBlocks.OSMIUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_anvil"), new BlockItem(MythicBlocks.PALLADIUM_ANVIL, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR).fireproof()));
        RegisterItem("platinum_anvil", MythicBlocks.PLATINUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("prometheum_anvil", MythicBlocks.PROMETHEUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("quadrillum_anvil", MythicBlocks.QUADRILLUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("quicksilver_anvil", MythicBlocks.QUICKSILVER_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("runite_anvil", MythicBlocks.RUNITE_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("silver_anvil", MythicBlocks.SILVER_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("star_platinum_anvil", MythicBlocks.STAR_PLATINUM_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("steel_anvil", MythicBlocks.STEEL_ANVIL, MythicMetals.MYTHICMETALS_DECOR);
        RegisterItem("stormyx_anvil", MythicBlocks.STORMYX_ANVIL, MythicMetals.MYTHICMETALS_DECOR);

        RegisterBlock("adamantite_anvil", MythicBlocks.ADAMANTITE_ANVIL);
        RegisterBlock("aetherium_anvil", MythicBlocks.AETHERIUM_ANVIL);
        RegisterBlock("aquarium_anvil", MythicBlocks.AQUARIUM_ANVIL);
        RegisterBlock("banglum_anvil", MythicBlocks.BANGLUM_ANVIL);
        RegisterBlock("bronze_anvil", MythicBlocks.BRONZE_ANVIL);
        RegisterBlock("carmot_anvil", MythicBlocks.CARMOT_ANVIL);
        RegisterBlock("celestium_anvil", MythicBlocks.CELESTIUM_ANVIL);
        RegisterBlock("discordium_anvil", MythicBlocks.DISCORDIUM_ANVIL);
        RegisterBlock("durasteel_anvil", MythicBlocks.DURASTEEL_ANVIL);
        RegisterBlock("etherite_anvil", MythicBlocks.ETHERITE_ANVIL);
        RegisterBlock("hallowed_anvil", MythicBlocks.HALLOWED_ANVIL);
        RegisterBlock("kyber_anvil", MythicBlocks.KYBER_ANVIL);
        RegisterBlock("manganese_anvil", MythicBlocks.MANGANESE_ANVIL);
        RegisterBlock("metallurgium_anvil", MythicBlocks.METALLURGIUM_ANVIL);
        RegisterBlock("midas_gold_anvil", MythicBlocks.MIDAS_GOLD_ANVIL);
        RegisterBlock("mythril_anvil", MythicBlocks.MYTHRIL_ANVIL);
        RegisterBlock("orichalcum_anvil", MythicBlocks.ORICHALCUM_ANVIL);
        RegisterBlock("osmium_anvil", MythicBlocks.OSMIUM_ANVIL);
        RegisterBlock("palladium_anvil", MythicBlocks.PALLADIUM_ANVIL);
        RegisterBlock("platinum_anvil", MythicBlocks.PLATINUM_ANVIL);
        RegisterBlock("prometheum_anvil", MythicBlocks.PROMETHEUM_ANVIL);
        RegisterBlock("quadrillum_anvil", MythicBlocks.QUADRILLUM_ANVIL);
        RegisterBlock("quicksilver_anvil", MythicBlocks.QUICKSILVER_ANVIL);
        RegisterBlock("runite_anvil", MythicBlocks.RUNITE_ANVIL);
        RegisterBlock("silver_anvil", MythicBlocks.SILVER_ANVIL);
        RegisterBlock("star_platinum_anvil", MythicBlocks.STAR_PLATINUM_ANVIL);
        RegisterBlock("steel_anvil", MythicBlocks.STEEL_ANVIL);
        RegisterBlock("stormyx_anvil", MythicBlocks.STORMYX_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.ADAMANTITE_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.AETHERIUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.AQUARIUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.BANGLUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.BRONZE_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.CARMOT_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.CELESTIUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.DISCORDIUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.DURASTEEL_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.ETHERITE_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.HALLOWED_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.KYBER_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.MANGANESE_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.METALLURGIUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.MIDAS_GOLD_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.MYTHRIL_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.ORICHALCUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.OSMIUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.PALLADIUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.PLATINUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.PROMETHEUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.QUADRILLUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.QUICKSILVER_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.RUNITE_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.SILVER_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.STAR_PLATINUM_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.STEEL_ANVIL);
        MythicBlocks.ANVILS.add(MythicBlocks.STORMYX_ANVIL);

        // Chains
        RegisterChainItem("adamantite_chain", MythicBlocks.ADAMANTITE_CHAIN);
        RegisterChainItem("aetherium_chain", MythicBlocks.AETHERIUM_CHAIN);
        RegisterChainItem("aquarium_chain", MythicBlocks.AQUARIUM_CHAIN);
        RegisterChainItem("banglum_chain", MythicBlocks.BANGLUM_CHAIN);
        RegisterChainItem("bronze_chain", MythicBlocks.BRONZE_CHAIN);
        RegisterChainItem("carmot_chain", MythicBlocks.CARMOT_CHAIN);
        RegisterChainItem("celestium_chain", MythicBlocks.CELESTIUM_CHAIN);
        RegisterChainItem("discordium_chain", MythicBlocks.DISCORDIUM_CHAIN);
        RegisterChainItem("durasteel_chain", MythicBlocks.DURASTEEL_CHAIN);
        RegisterChainItem("etherite_chain", MythicBlocks.ETHERITE_CHAIN);
        RegisterChainItem("hallowed_chain", MythicBlocks.HALLOWED_CHAIN);
        RegisterChainItem("kyber_chain", MythicBlocks.KYBER_CHAIN);
        RegisterChainItem("manganese_chain", MythicBlocks.MANGANESE_CHAIN);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.CHAIN_ID, "metallurgium_chain"), new BlockItem(MythicBlocks.METALLURGIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR).fireproof()));
        RegisterChainItem("midas_gold_chain", MythicBlocks.MIDAS_GOLD_CHAIN);
        RegisterChainItem("mythril_chain", MythicBlocks.MYTHRIL_CHAIN);
        RegisterChainItem("orichalcum_chain", MythicBlocks.ORICHALCUM_CHAIN);
        RegisterChainItem("osmium_chain", MythicBlocks.OSMIUM_CHAIN);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.CHAIN_ID, "palladium_chain"), new BlockItem(MythicBlocks.PALLADIUM_CHAIN, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR).fireproof()));
        RegisterChainItem("platinum_chain", MythicBlocks.PLATINUM_CHAIN);
        RegisterChainItem("prometheum_chain", MythicBlocks.PROMETHEUM_CHAIN);
        RegisterChainItem("quadrillum_chain", MythicBlocks.QUADRILLUM_CHAIN);
        RegisterChainItem("quicksilver_chain", MythicBlocks.QUICKSILVER_CHAIN);
        RegisterChainItem("runite_chain", MythicBlocks.RUNITE_CHAIN);
        RegisterChainItem("silver_chain", MythicBlocks.SILVER_CHAIN);
        RegisterChainItem("star_platinum_chain", MythicBlocks.STAR_PLATINUM_CHAIN);
        RegisterChainItem("steel_chain", MythicBlocks.STEEL_CHAIN);
        RegisterChainItem("stormyx_chain", MythicBlocks.STORMYX_CHAIN);

        RegisterChainBlock("adamantite_chain", MythicBlocks.ADAMANTITE_CHAIN);
        RegisterChainBlock("aetherium_chain", MythicBlocks.AETHERIUM_CHAIN);
        RegisterChainBlock("aquarium_chain", MythicBlocks.AQUARIUM_CHAIN);
        RegisterChainBlock("banglum_chain", MythicBlocks.BANGLUM_CHAIN);
        RegisterChainBlock("bronze_chain", MythicBlocks.BRONZE_CHAIN);
        RegisterChainBlock("carmot_chain", MythicBlocks.CARMOT_CHAIN);
        RegisterChainBlock("celestium_chain", MythicBlocks.CELESTIUM_CHAIN);
        RegisterChainBlock("discordium_chain", MythicBlocks.DISCORDIUM_CHAIN);
        RegisterChainBlock("durasteel_chain", MythicBlocks.DURASTEEL_CHAIN);
        RegisterChainBlock("etherite_chain", MythicBlocks.ETHERITE_CHAIN);
        RegisterChainBlock("hallowed_chain", MythicBlocks.HALLOWED_CHAIN);
        RegisterChainBlock("kyber_chain", MythicBlocks.KYBER_CHAIN);
        RegisterChainBlock("manganese_chain", MythicBlocks.MANGANESE_CHAIN);
        RegisterChainBlock("metallurgium_chain", MythicBlocks.METALLURGIUM_CHAIN);
        RegisterChainBlock("midas_gold_chain", MythicBlocks.MIDAS_GOLD_CHAIN);
        RegisterChainBlock("mythril_chain", MythicBlocks.MYTHRIL_CHAIN);
        RegisterChainBlock("orichalcum_chain", MythicBlocks.ORICHALCUM_CHAIN);
        RegisterChainBlock("osmium_chain", MythicBlocks.OSMIUM_CHAIN);
        RegisterChainBlock("palladium_chain", MythicBlocks.PALLADIUM_CHAIN);
        RegisterChainBlock("platinum_chain", MythicBlocks.PLATINUM_CHAIN);
        RegisterChainBlock("prometheum_chain", MythicBlocks.PROMETHEUM_CHAIN);
        RegisterChainBlock("quadrillum_chain", MythicBlocks.QUADRILLUM_CHAIN);
        RegisterChainBlock("quicksilver_chain", MythicBlocks.QUICKSILVER_CHAIN);
        RegisterChainBlock("runite_chain", MythicBlocks.RUNITE_CHAIN);
        RegisterChainBlock("silver_chain", MythicBlocks.SILVER_CHAIN);
        RegisterChainBlock("star_platinum_chain", MythicBlocks.STAR_PLATINUM_CHAIN);
        RegisterChainBlock("steel_chain", MythicBlocks.STEEL_CHAIN);
        RegisterChainBlock("stormyx_chain", MythicBlocks.STORMYX_CHAIN);
    }

    private static void RegisterBlock(String path, Block block) {
        Registry.register(Registry.BLOCK, new Identifier(MythicMetals.MOD_ID, path), block);
    }

    private static void RegisterItem(String path, Block block, ItemGroup group) {
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, path), new BlockItem(block, new Item.Settings().group(group)));
    }

    private static void RegisterChainItem(String path, Block block) {
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.CHAIN_ID, path), new BlockItem(block, new Item.Settings().group(MythicMetals.MYTHICMETALS_DECOR)));
    }

    private static void RegisterChainBlock(String path, Block block) {
        Registry.register(Registry.BLOCK, new Identifier(MythicMetals.CHAIN_ID, path), block);
    }
}
