package nourl.mythicmetals.registry;

import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import nourl.mythicmetals.MythicMetals;

public class RegisterItems {
    //Normal Ingots
    public static final Item ADAMANTITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AETHERIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AQUARIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ARGONIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BANGLUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BRONZE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CARMOT_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CELESTIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DISCORDIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DURASTEEL_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ELECTRUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ETHERITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item HALLOWED_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item KYBER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MANGANESE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item METALLURGIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item MIDAS_GOLD_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MYTHRIL_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ORICHALCUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item OSMIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PALLADIUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item PLATINUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PROMETHEUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUADRILLUM_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUICKSILVER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RUNITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item SILVER_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STARRITE_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STEEL_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STORMYX_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TIN_INGOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item UNOBTAINIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item VERMICULITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));

    // Raw Ores
    public static final Item RAW_ADAMANTITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_AETHERIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_AQUARIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_BANGLUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_CARMOT = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_KYBER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_MANGANESE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_MIDAS_GOLD = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_MYTHRIL = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_ORICHALCUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_OSMIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_PALLADIUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item RAW_PLATINUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_PROMETHEUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_QUADRILLUM = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_RUNITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_SILVER = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_STARRITE = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_STORMYX = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RAW_TIN = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));

    // Nuggets
    public static final Item ADAMANTITE_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AETHERIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AQUARIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ARGONIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BANGLUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BRONZE_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CARMOT_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CELESTIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item COPPER_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DISCORDIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DURASTEEL_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ELECTRUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ETHERITE_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item HALLOWED_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item KYBER_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MANGANESE_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item METALLURGIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item MIDAS_GOLD_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MYTHRIL_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ORICHALCUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item OSMIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PALLADIUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item PLATINUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PROMETHEUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUADRILLUM_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUICKSILVER_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RUNITE_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item SILVER_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STARRITE_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STEEL_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STORMYX_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TIN_NUGGET = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));

    // Dusts
    public static final Item ADAMANTITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AETHERIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item AQUARIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ARGONIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BANGLUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item BRONZE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CARMOT_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item CELESTIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item COPPER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DISCORDIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item DURASTEEL_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ELECTRUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ETHERITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item GOLD_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item HALLOWED_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item KYBER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MANGANESE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item METALLURGIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item MIDAS_GOLD_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item MYTHRIL_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item ORICHALCUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item OSMIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PALLADIUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS).fireproof());
    public static final Item PLATINUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item PROMETHEUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUADRILLUM_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item QUICKSILVER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item RUNITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item SILVER_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STARRITE_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STEEL_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item STORMYX_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));
    public static final Item TIN_DUST = new Item(new Item.Settings().group(MythicMetals.MYTHICMETALS));


    public static void registerItems() {
        //Register Ingots
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_ingot"), ADAMANTITE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_ingot"), AETHERIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_ingot"), AQUARIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_ingot"), ARGONIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_ingot"), BANGLUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_ingot"), BRONZE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_ingot"), CARMOT_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_ingot"), CELESTIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_ingot"), DISCORDIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_ingot"), DURASTEEL_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_ingot"), ELECTRUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_ingot"), ETHERITE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_ingot"), HALLOWED_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_ingot"), KYBER_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_ingot"), MANGANESE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_ingot"), METALLURGIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_ingot"), MIDAS_GOLD_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_ingot"), MYTHRIL_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_ingot"), ORICHALCUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_ingot"), OSMIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_ingot"), PLATINUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_ingot"), PROMETHEUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_ingot"), QUADRILLUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_ingot"), QUICKSILVER_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_ingot"), RUNITE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_ingot"), SILVER_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_ingot"), STARRITE_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_ingot"), STEEL_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_ingot"), STORMYX_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tin_ingot"), TIN_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_ingot"), PALLADIUM_INGOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "unobtainium"), UNOBTAINIUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "vermiculite"), VERMICULITE);

        //Register Raw Ore
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_adamantite"), RAW_ADAMANTITE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_aetherium"), RAW_AETHERIUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_aquarium"), RAW_AQUARIUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_banglum"), RAW_BANGLUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_carmot"), RAW_CARMOT);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_kyber"), RAW_KYBER);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_manganese"), RAW_MANGANESE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_midas_gold"), RAW_MIDAS_GOLD);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_mythril"), RAW_MYTHRIL);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_orichalcum"), RAW_ORICHALCUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_osmium"), RAW_OSMIUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_platinum"), RAW_PLATINUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_prometheum"), RAW_PROMETHEUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_quadrillum"), RAW_QUADRILLUM);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_runite"), RAW_RUNITE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_silver"), RAW_SILVER);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_starrite"), RAW_STARRITE);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_stormyx"), RAW_STORMYX);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_tin"), RAW_TIN);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "raw_palladium"), RAW_PALLADIUM);
    }
    public static void registerDusts() {
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_dust"), ADAMANTITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_dust"), AETHERIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_dust"), AQUARIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_dust"), ARGONIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_dust"), BANGLUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_dust"), BRONZE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_dust"), CARMOT_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_dust"), CELESTIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_dust"), COPPER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_dust"), DISCORDIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_dust"), DURASTEEL_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_dust"), ELECTRUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_dust"), ETHERITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "gold_dust"), GOLD_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_dust"), HALLOWED_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_dust"), KYBER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_dust"), MANGANESE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_dust"), METALLURGIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_dust"), MIDAS_GOLD_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_dust"), MYTHRIL_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_dust"), ORICHALCUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_dust"), OSMIUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_dust"), PLATINUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_dust"), PROMETHEUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_dust"), QUADRILLUM_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_dust"), QUICKSILVER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_dust"), RUNITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_dust"), SILVER_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_dust"), STARRITE_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_dust"), STEEL_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_dust"), STORMYX_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tin_dust"), TIN_DUST);
    Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_dust"), PALLADIUM_DUST);
    }

    public static void registerNuggets() {
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "adamantite_nugget"), ADAMANTITE_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aetherium_nugget"), AETHERIUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "aquarium_nugget"), AQUARIUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "argonium_nugget"), ARGONIUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "banglum_nugget"), BANGLUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "bronze_nugget"), BRONZE_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "carmot_nugget"), CARMOT_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "celestium_nugget"), CELESTIUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "copper_nugget"), COPPER_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "discordium_nugget"), DISCORDIUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "durasteel_nugget"), DURASTEEL_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "electrum_nugget"), ELECTRUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "etherite_nugget"), ETHERITE_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "hallowed_nugget"), HALLOWED_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "kyber_nugget"), KYBER_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "manganese_nugget"), MANGANESE_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "metallurgium_nugget"), METALLURGIUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "midas_gold_nugget"), MIDAS_GOLD_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "mythril_nugget"), MYTHRIL_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "orichalcum_nugget"), ORICHALCUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "osmium_nugget"), OSMIUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "platinum_nugget"), PLATINUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "prometheum_nugget"), PROMETHEUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quadrillum_nugget"), QUADRILLUM_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "quicksilver_nugget"), QUICKSILVER_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "runite_nugget"), RUNITE_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "silver_nugget"), SILVER_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "starrite_nugget"), STARRITE_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "steel_nugget"), STEEL_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "stormyx_nugget"), STORMYX_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "tin_nugget"), TIN_NUGGET);
        Registry.register(Registry.ITEM, new Identifier(MythicMetals.MOD_ID, "palladium_nugget"), PALLADIUM_NUGGET);
    }
}
